#!/usr/bin/env bash
# Materialize the SWAT staging runtime env at /opt/swat/.env.
#
# With dotenvx, the bulk of the backend config lives in the committed, ENCRYPTED
# infra/env/backend/.env.staging baked into the image (as /app/.env.staging). The
# only thing the container needs at runtime is the private key to decrypt it — so
# this file contains just that key, pulled from SSM Parameter Store via the EC2
# instance role. NODE_ENV / BE_PORT / REDIS_URL are set by compose.staging.yml.
#
#   bash infra/seed-env-from-ssm.sh
set -euo pipefail

REGION="${AWS_REGION:-ap-southeast-3}"
OUT=/opt/swat/.env

get() {
  aws ssm get-parameter --region "$REGION" --name "$1" --with-decryption \
    --query Parameter.Value --output text
}

# Stored as BE_DOTENV_PRIVATE_KEY; the runtime var dotenvx needs is
# DOTENV_PRIVATE_KEY_STAGING (derived from the .env.staging filename).
DOTENV_PRIVATE_KEY_STAGING="$(get /swat/staging/BE_DOTENV_PRIVATE_KEY)"

# /opt/swat must be readable by the user that runs `docker compose` (ec2-user) so
# the compose `env_file:` can be read — the Docker CLI reads it as the invoking user.
sudo mkdir -p /opt/swat
sudo chown -R "$(id -un)":"$(id -gn)" /opt/swat
umask 077
cat > "$OUT" <<EOF
# Generated by infra/seed-env-from-ssm.sh — do not edit by hand.
# Single dotenvx private key; everything else is in the encrypted
# infra/env/backend/.env.staging baked into the backend image.
DOTENV_PRIVATE_KEY_STAGING=${DOTENV_PRIVATE_KEY_STAGING}
EOF

sudo chmod 600 "$OUT"
echo "Wrote $OUT (dotenvx private key only)"
