/**
 * Pure legacy-row → Prisma `createMany` input mappers. Strategy (per
 * `specs/04-migration.md` §7): new PKs are UUID v7 (generated by Prisma's
 * `@default(uuid(7))`), and the legacy numeric PK is stored as `legacyId` for
 * traceability. A legacy FK can therefore NOT be copied verbatim — the loader
 * inserts parents first, builds a `legacyId → new UUID` map per table, and the
 * child mapper resolves each legacy FK through that map ({@link resolveFk}).
 * Audit timestamps are set to the migration `now`.
 *
 * No DB access here — every mapper is a deterministic transform, unit-tested
 * without infrastructure (the live run is the operator's on-prem step).
 */
import { type Prisma } from '@prisma/client';

/** legacy numeric id → migrated UUID, built by the loader after each parent insert. */
export type LegacyIdMap = ReadonlyMap<number, string>;

/**
 * Resolve a required legacy FK to its migrated UUID. Throws loudly on a miss so
 * an orphaned reference fails the load instead of silently writing a bad row
 * (which `@db.Uuid` would reject anyway). `ctx` names the FK for the error.
 */
export function resolveFk(map: LegacyIdMap, legacyId: number, ctx: string): string {
  const id = map.get(legacyId);
  if (id === undefined) {
    throw new Error(`FK ${ctx}: tidak ada baris hasil migrasi untuk legacyId=${legacyId}.`);
  }
  return id;
}

/**
 * Build a `legacy numeric id → migrated UUID` lookup from a just-loaded parent
 * table (rows selected as `{ id, legacyId }`). Rows without a `legacyId` are
 * skipped. The loader calls this after each parent insert and feeds the result
 * to the child FK mappers above.
 */
export function toLegacyMap(
  rows: ReadonlyArray<{ id: string; legacyId: number | bigint | null }>,
): Map<number, string> {
  const map = new Map<number, string>();
  for (const row of rows) {
    if (row.legacyId !== null) {
      map.set(Number(row.legacyId), row.id);
    }
  }
  return map;
}

import {
  mapEmploymentStatus,
  mapDisposalPermitStatus,
  mapRouteCategory,
  mapSiteType,
  mapVehicleStatus,
} from './enums';
import {
  type LegacyDailyTonnage,
  type LegacyDriver,
  type LegacyDriverLicense,
  type LegacyFuel,
  type LegacyFuelCategory,
  type LegacyDisposalPermit,
  type LegacyLevy,
  type LegacyLicenseClass,
  type LegacyNameMapRow,
  type LegacyRoute,
  type LegacySite,
  type LegacyVehicle,
  type LegacyVehicleType,
  type LegacyVehicleModel,
  type LegacyVehicleWasteSource,
  type LegacyWasteSource,
} from './legacy-types';
import {
  clampNonNegative,
  fixDate,
  fixGps,
  fixYear,
  nonNegativeOrNull,
  trimOrNull,
} from './transforms';

const audit = (now: Date): { createdAt: Date; updatedAt: Date } => ({
  createdAt: now,
  updatedAt: now,
});

export function mapVehicleType(r: LegacyVehicleType, now: Date): Prisma.VehicleTypeCreateManyInput {
  return {
    legacyId: r.APLIKASIKENDARAAN_ID,
    name: r.APLIKASIKENDARAAN_NAMA,
    ...audit(now),
  };
}

export function mapFuelCategory(
  r: LegacyFuelCategory,
  now: Date,
): Prisma.FuelCategoryCreateManyInput {
  return {
    legacyId: r.KATEGORIBAHANBAKAR_ID,
    name: r.KATEGORIBAHANBAKAR_NAMA,
    ...audit(now),
  };
}

export function mapFuel(
  r: LegacyFuel,
  now: Date,
  fuelCategoryMap: LegacyIdMap,
): Prisma.FuelCreateManyInput {
  return {
    legacyId: r.BAHANBAKAR_ID,
    fuelCategoryId: resolveFk(fuelCategoryMap, r.KATEGORIBAHANBAKAR_ID, 'fuel.fuelCategoryId'),
    name: r.BAHANBAKAR_NAMA,
    pricePerLiter: clampNonNegative(r.BAHANBAKAR_HARGAPERLITER),
    ...audit(now),
  };
}

export function mapLicenseClass(
  r: LegacyLicenseClass,
  now: Date,
): Prisma.LicenseClassCreateManyInput {
  return {
    legacyId: r.SIM_ID,
    name: r.SIM_NAMA,
    ...audit(now),
  };
}

export function mapSite(r: LegacySite, now: Date): Prisma.SiteCreateManyInput {
  const { latitude, longitude } = fixGps(r.SPOT_LATITUDE, r.SPOT_LONGITUDE);
  return {
    legacyId: r.SPOT_ID,
    type: mapSiteType(r.KATEGORISPOT_ID),
    name: r.SPOT_NAMA,
    address: r.SPOT_ALAMAT,
    latitude,
    longitude,
    ...audit(now),
  };
}

export function mapRoute(
  r: LegacyRoute,
  now: Date,
  siteMap: LegacyIdMap,
): Prisma.RouteCreateManyInput {
  return {
    legacyId: r.RUTE_ID,
    category: mapRouteCategory(r.KATEGORIRUTE_ID),
    originSiteId: resolveFk(siteMap, r.SPOT_ASAL_ID, 'route.originSiteId'),
    destinationSiteId: resolveFk(siteMap, r.SPOT_TUJUAN_ID, 'route.destinationSiteId'),
    distanceKm: clampNonNegative(r.RUTE_JARAK),
    ...audit(now),
  };
}

export function mapWasteSource(r: LegacyWasteSource, now: Date): Prisma.WasteSourceCreateManyInput {
  return {
    legacyId: r.KATEGORISUMBERSAMPAH_ID,
    code: r.KATEGORISUMBERSAMPAH_KODE,
    name: r.KATEGORISUMBERSAMPAH_NAMA,
    notes: trimOrNull(r.KATEGORISUMBERSAMPAH_KETERANGAN),
    ...audit(now),
  };
}

export function mapVehicleModel(
  r: LegacyVehicleModel,
  now: Date,
  applicationMap: LegacyIdMap,
  fuelMap: LegacyIdMap,
): Prisma.VehicleModelCreateManyInput {
  return {
    legacyId: r.KATEGORIKENDARAAN_ID,
    vehicleTypeId: resolveFk(applicationMap, r.APLIKASIKENDARAAN_ID, 'vehicleModel.vehicleTypeId'),
    fuelId: resolveFk(fuelMap, r.BAHANBAKAR_ID, 'vehicleModel.fuelId'),
    brand: r.KATEGORIKENDARAAN_MERK,
    fuelTankCapacity: clampNonNegative(r.KATEGORIKENDARAAN_KAPASITASBAHANBAKAR),
    normalFuelRatio: clampNonNegative(r.KATEGORIKENDARAAN_RASIOBAHANBAKARNORMAL) || 1,
    normalTareWeight: clampNonNegative(r.KATEGORIKENDARAAN_BERATKOSONGNORMAL),
    maxNetLoad: nonNegativeOrNull(r.KATEGORIKENDARAAN_BERATBERSIHMUATANMAKSIMUM),
    maxNetVolume: nonNegativeOrNull(r.KATEGORIKENDARAAN_VOLUMEBERSIHMUATANMAKSIMUM),
    wheelCount: clampNonNegative(r.KATEGORIKENDARAAN_JUMLAHRODA),
    ...audit(now),
  };
}

export function mapVehicle(
  r: LegacyVehicle,
  now: Date,
  siteMap: LegacyIdMap,
  modelMap: LegacyIdMap,
): Prisma.VehicleCreateManyInput {
  return {
    legacyId: r.KENDARAAN_ID,
    poolSiteId: resolveFk(siteMap, r.SPOT_POOL_ID, 'vehicle.poolSiteId'),
    modelId: resolveFk(modelMap, r.KATEGORIKENDARAAN_ID, 'vehicle.modelId'),
    status: mapVehicleStatus(r.STATUSKENDARAAN_ID),
    plateNumber: r.KENDARAAN_NOMORPOLISI,
    chassisNumber: r.KENDARAAN_NOMORRANGKA,
    engineNumber: r.KENDARAAN_NOMORMESIN,
    manufactureYear: fixYear(r.KENDARAAN_TAHUNPEMBUATAN, now),
    currentFuelRatio: clampNonNegative(r.KENDARAAN_RASIOBAHANBAKARTERKINI) || 1,
    currentTareWeight: clampNonNegative(r.KENDARAAN_BERATKOSONGTERKINI),
    currentOdometer: clampNonNegative(r.KENDARAAN_KMTERKINI),
    // STNK/tax expiry are NOT NULL in the new schema; a zero-date legacy value
    // falls back to the migration date so the row still loads (flagged in verify).
    registrationExpiry: fixDate(r.KENDARAAN_MASABERLAKUSTNK) ?? now,
    taxExpiry: fixDate(r.KENDARAAN_MASABERLAKUPAJAKSTNK) ?? now,
    notes: trimOrNull(r.KENDARAAN_KETERANGAN),
    ...audit(now),
  };
}

export function mapVehicleWasteSource(
  r: LegacyVehicleWasteSource,
  vehicleMap: LegacyIdMap,
  wasteSourceMap: LegacyIdMap,
): Prisma.VehicleWasteSourceCreateManyInput {
  return {
    vehicleId: resolveFk(vehicleMap, r.KENDARAAN_ID, 'vehicleWasteSource.vehicleId'),
    wasteSourceId: resolveFk(
      wasteSourceMap,
      r.KATEGORISUMBERSAMPAH_ID,
      'vehicleWasteSource.wasteSourceId',
    ),
  };
}

export function mapDriver(
  r: LegacyDriver,
  now: Date,
  siteMap: LegacyIdMap,
): Prisma.DriverCreateManyInput {
  return {
    legacyId: r.PENGEMUDI_ID,
    poolSiteId: resolveFk(siteMap, r.SPOT_POOL_ID, 'driver.poolSiteId'),
    employmentStatus: mapEmploymentStatus(r.STATUSKEPEGAWAIAN_ID),
    name: r.PENGEMUDI_NAMA,
    idCardNumber: r.PENGEMUDI_NOMORKTP,
    originAddress: r.PENGEMUDI_ALAMATASAL,
    currentAddress: r.PENGEMUDI_ALAMATDOMISILI,
    // Birth date is NOT NULL; a missing/zero legacy date falls back to the epoch.
    birthDate: fixDate(r.PENGEMUDI_TANGGALLAHIR) ?? new Date('1970-01-01T00:00:00.000Z'),
    contact: r.PENGEMUDI_KONTAK,
    safetyTraining: trimOrNull(r.PENGEMUDI_PELATIHANSAFETY),
    notes: trimOrNull(r.PENGEMUDI_KETERANGAN),
    ...audit(now),
  };
}

export function mapDriverLicense(
  r: LegacyDriverLicense,
  now: Date,
  driverMap: LegacyIdMap,
  licenseClassMap: LegacyIdMap,
): Prisma.DriverLicenseCreateManyInput {
  return {
    legacyId: r.KEPEMILIKANSIM_ID,
    driverId: resolveFk(driverMap, r.PENGEMUDI_ID, 'driverLicense.driverId'),
    licenseClassId: resolveFk(licenseClassMap, r.SIM_ID, 'driverLicense.licenseClassId'),
    licenseNumber: r.KEPEMILIKANSIM_NOMORSIM,
    expiry: fixDate(r.KEPEMILIKANSIM_MASABERLAKUSIM) ?? now,
    ...audit(now),
  };
}

export function mapDisposalPermit(
  r: LegacyDisposalPermit,
  now: Date,
  systemUserId: string,
  vehicleMap: LegacyIdMap,
  siteMap: LegacyIdMap,
): Prisma.DisposalPermitCreateManyInput {
  return {
    legacyId: r.JATAHKITIR_ID,
    vehicleId: resolveFk(vehicleMap, r.KENDARAAN_ID, 'disposalPermit.vehicleId'),
    siteId: resolveFk(siteMap, r.SPOT_ID, 'disposalPermit.siteId'),
    status: mapDisposalPermitStatus(r.STATUSJATAHKITIR_ID),
    issuedAt: fixDate(r.JATAHKITIR_WAKTUDITERBITKAN) ?? now,
    validFrom: fixDate(r.JATAHKITIR_MASABERLAKUAWAL) ?? now,
    validTo: fixDate(r.JATAHKITIR_MASABERLAKUAKHIR) ?? now,
    createdById: systemUserId,
    ...audit(now),
  };
}

export function mapDailyTonnage(
  r: LegacyDailyTonnage,
  now: Date,
): Prisma.DailyTonnageCreateManyInput {
  return {
    legacyId: r.TONASE_ID,
    // amount is BigInt (kg); legacy TONASE_NOMINAL is a double — round to integer.
    amount: BigInt(Math.round(r.TONASE_NOMINAL ?? 0)),
    date: fixDate(r.TONASE_TANGGAL) ?? now,
    ...audit(now),
  };
}

export function mapLevy(
  r: LegacyLevy,
  now: Date,
  systemUserId: string,
): Prisma.LevyCreateManyInput {
  return {
    legacyId: r.ID_KATEGORI_RETRIBUSI,
    categoryName: r.NAMA_KATEGORI_RETRIBUSI,
    date: fixDate(r.TANGGAL) ?? now,
    amount: BigInt(r.JUMLAH ?? 0),
    createdById: systemUserId,
    ...audit(now),
  };
}

export function mapNameMap(r: LegacyNameMapRow, now: Date): Prisma.LegacyNameMapCreateManyInput {
  return {
    si: trimOrNull(r.si),
    swat: trimOrNull(r.swat),
    ...audit(now),
  };
}
