-- ===========================================================================
-- Monthly RANGE partitioning for the high-volume transactional tables.
-- Runs AFTER the Prisma-generated init migration, which created these tables
-- as ordinary tables. PostgreSQL cannot convert an ordinary table into a
-- partitioned one in place, so we drop the (empty, greenfield) tables and
-- recreate them as partitioned by `operationDate`.
--
-- Design notes:
--  * Partition key `operationDate` must be part of every PK/UNIQUE → PKs become
--    (operationDate, id). `id` stays globally unique in practice via IDENTITY.
--  * `legacyId` cannot be globally UNIQUE on a partitioned table (would need the
--    key) → demoted to a non-unique index. No legacy data exists yet in Phase 0.
--  * Cross-partition FKs include the key: HaulAssignment(operationDate, haulId)
--    → Haul(operationDate, id); Trip(operationDate, haulAssignmentId) →
--    HaulAssignment(operationDate, id). The app sets the denormalized
--    operationDate consistently down the chain.
--  * TpaInboundLog has no `operationDate` in the Prisma model; we add a physical
--    `operationDate DATE NOT NULL DEFAULT CURRENT_DATE` for partition routing.
--    Prisma is unaware of it (harmless: Prisma selects explicit columns).
--  * Child partitions inherit parent indexes as LOCAL indexes (PG11+).
-- ===========================================================================

-- Nothing references these tables via FK (Photo is polymorphic; TpaInboundLog.tripId
-- has no FK). Safe to drop and recreate. CASCADE clears their own constraints/sequences.
DROP TABLE IF EXISTS "Trip" CASCADE;
DROP TABLE IF EXISTS "HaulAssignment" CASCADE;
DROP TABLE IF EXISTS "Haul" CASCADE;
DROP TABLE IF EXISTS "TpaInboundLog" CASCADE;

-- ---------------------------------------------------------------------------
-- Haul
-- ---------------------------------------------------------------------------
CREATE TABLE "Haul" (
  "id"               BIGINT       GENERATED BY DEFAULT AS IDENTITY,
  "legacyId"         BIGINT,
  "transactionDayId" INTEGER      NOT NULL,
  "vehicleId"        INTEGER      NOT NULL,
  "operationDate"    DATE         NOT NULL DEFAULT CURRENT_DATE,
  "status"           "DayStatus"  NOT NULL DEFAULT 'IN_PROGRESS',
  "notes"            VARCHAR(256),
  "createdAt"        TIMESTAMPTZ(6) NOT NULL DEFAULT now(),
  "updatedAt"        TIMESTAMPTZ(6) NOT NULL,
  CONSTRAINT "Haul_pkey" PRIMARY KEY ("operationDate", "id"),
  CONSTRAINT "Haul_operationDate_transactionDayId_vehicleId_key"
    UNIQUE ("operationDate", "transactionDayId", "vehicleId"),
  CONSTRAINT "Haul_transactionDayId_fkey"
    FOREIGN KEY ("transactionDayId") REFERENCES "TransactionDay"("id") ON UPDATE CASCADE ON DELETE RESTRICT,
  CONSTRAINT "Haul_vehicleId_fkey"
    FOREIGN KEY ("vehicleId") REFERENCES "Vehicle"("id") ON UPDATE CASCADE ON DELETE RESTRICT
) PARTITION BY RANGE ("operationDate");

CREATE INDEX "Haul_operationDate_idx" ON "Haul" ("operationDate");
CREATE INDEX "Haul_legacyId_idx" ON "Haul" ("legacyId");

-- ---------------------------------------------------------------------------
-- HaulAssignment
-- ---------------------------------------------------------------------------
CREATE TABLE "HaulAssignment" (
  "id"                   BIGINT       GENERATED BY DEFAULT AS IDENTITY,
  "legacyId"             BIGINT,
  "haulId"               BIGINT       NOT NULL,
  "driverId"             INTEGER      NOT NULL,
  "crewScheduleId"       INTEGER,
  "operationDate"        DATE         NOT NULL DEFAULT CURRENT_DATE,
  "status"               "DayStatus"  NOT NULL DEFAULT 'IN_PROGRESS',
  "departTargetOdometer" INTEGER      NOT NULL DEFAULT 0,
  "departActualOdometer" INTEGER,
  "returnTargetOdometer" INTEGER      NOT NULL DEFAULT 0,
  "returnActualOdometer" INTEGER,
  "departTargetTime"     TIMESTAMPTZ(6),
  "departActualTime"     TIMESTAMPTZ(6),
  "returnTargetTime"     TIMESTAMPTZ(6),
  "returnActualTime"     TIMESTAMPTZ(6),
  "notes"                VARCHAR(256),
  "createdAt"            TIMESTAMPTZ(6) NOT NULL DEFAULT now(),
  "updatedAt"            TIMESTAMPTZ(6) NOT NULL,
  "createdById"          INTEGER,
  "updatedById"          INTEGER,
  CONSTRAINT "HaulAssignment_pkey" PRIMARY KEY ("operationDate", "id"),
  CONSTRAINT "HaulAssignment_operationDate_haulId_fkey"
    FOREIGN KEY ("operationDate", "haulId") REFERENCES "Haul"("operationDate", "id") ON UPDATE CASCADE ON DELETE RESTRICT,
  CONSTRAINT "HaulAssignment_driverId_fkey"
    FOREIGN KEY ("driverId") REFERENCES "Driver"("id") ON UPDATE CASCADE ON DELETE RESTRICT,
  CONSTRAINT "HaulAssignment_crewScheduleId_fkey"
    FOREIGN KEY ("crewScheduleId") REFERENCES "CrewSchedule"("id") ON UPDATE CASCADE ON DELETE SET NULL,
  CONSTRAINT "HaulAssignment_createdById_fkey"
    FOREIGN KEY ("createdById") REFERENCES "User"("id") ON UPDATE CASCADE ON DELETE SET NULL,
  CONSTRAINT "HaulAssignment_updatedById_fkey"
    FOREIGN KEY ("updatedById") REFERENCES "User"("id") ON UPDATE CASCADE ON DELETE SET NULL
) PARTITION BY RANGE ("operationDate");

CREATE INDEX "HaulAssignment_haulId_idx" ON "HaulAssignment" ("haulId");
CREATE INDEX "HaulAssignment_operationDate_idx" ON "HaulAssignment" ("operationDate");
CREATE INDEX "HaulAssignment_legacyId_idx" ON "HaulAssignment" ("legacyId");

-- ---------------------------------------------------------------------------
-- Trip
-- ---------------------------------------------------------------------------
CREATE TABLE "Trip" (
  "id"                  BIGINT       GENERATED BY DEFAULT AS IDENTITY,
  "legacyId"            BIGINT,
  "haulAssignmentId"    BIGINT       NOT NULL,
  "routeId"             INTEGER,
  "recordedById"        INTEGER,
  "operationDate"       DATE         NOT NULL DEFAULT CURRENT_DATE,
  "status"              "TripStatus" NOT NULL DEFAULT 'IN_PROGRESS',
  "name"                VARCHAR(256) NOT NULL,
  "targetTime"          TIMESTAMPTZ(6),
  "actualTime"          TIMESTAMPTZ(6),
  "targetOdometer"      INTEGER      NOT NULL DEFAULT 0,
  "actualOdometer"      INTEGER      NOT NULL DEFAULT 0,
  "tareWeight"          INTEGER      NOT NULL DEFAULT 0,
  "grossWeight"         INTEGER,
  "netWeight"           INTEGER,
  "wasteVolume"         INTEGER,
  "fuelRequestedLiters" DECIMAL(8,2),
  "fuelApprovedLiters"  DECIMAL(8,2),
  "scheduledEntryAt"    TIMESTAMPTZ(6),
  "realizationEntryAt"  TIMESTAMPTZ(6),
  "notes"               VARCHAR(512),
  "createdAt"           TIMESTAMPTZ(6) NOT NULL DEFAULT now(),
  "updatedAt"           TIMESTAMPTZ(6) NOT NULL,
  "createdById"         INTEGER,
  "updatedById"         INTEGER,
  "verifiedById"        INTEGER,
  "verifiedAt"          TIMESTAMPTZ(6),
  CONSTRAINT "Trip_pkey" PRIMARY KEY ("operationDate", "id"),
  CONSTRAINT "Trip_operationDate_haulAssignmentId_fkey"
    FOREIGN KEY ("operationDate", "haulAssignmentId") REFERENCES "HaulAssignment"("operationDate", "id") ON UPDATE CASCADE ON DELETE RESTRICT,
  CONSTRAINT "Trip_routeId_fkey"
    FOREIGN KEY ("routeId") REFERENCES "Route"("id") ON UPDATE CASCADE ON DELETE SET NULL,
  CONSTRAINT "Trip_recordedById_fkey"
    FOREIGN KEY ("recordedById") REFERENCES "User"("id") ON UPDATE CASCADE ON DELETE SET NULL,
  CONSTRAINT "Trip_createdById_fkey"
    FOREIGN KEY ("createdById") REFERENCES "User"("id") ON UPDATE CASCADE ON DELETE SET NULL,
  CONSTRAINT "Trip_updatedById_fkey"
    FOREIGN KEY ("updatedById") REFERENCES "User"("id") ON UPDATE CASCADE ON DELETE SET NULL,
  CONSTRAINT "Trip_verifiedById_fkey"
    FOREIGN KEY ("verifiedById") REFERENCES "User"("id") ON UPDATE CASCADE ON DELETE SET NULL,
  CONSTRAINT "Trip_grossWeight_gte_tareWeight"
    CHECK ("grossWeight" IS NULL OR "grossWeight" >= "tareWeight"),
  CONSTRAINT "Trip_fuelApproved_lte_requested"
    CHECK ("fuelApprovedLiters" IS NULL OR "fuelRequestedLiters" IS NULL OR "fuelApprovedLiters" <= "fuelRequestedLiters")
) PARTITION BY RANGE ("operationDate");

CREATE INDEX "Trip_haulAssignmentId_idx" ON "Trip" ("haulAssignmentId");
CREATE INDEX "Trip_routeId_idx" ON "Trip" ("routeId");
CREATE INDEX "Trip_status_idx" ON "Trip" ("status");
CREATE INDEX "Trip_operationDate_idx" ON "Trip" ("operationDate");
CREATE INDEX "Trip_legacyId_idx" ON "Trip" ("legacyId");

-- ---------------------------------------------------------------------------
-- TpaInboundLog (weighbridge log) — partition by a physical operationDate.
-- ---------------------------------------------------------------------------
CREATE TABLE "TpaInboundLog" (
  "id"            INTEGER      GENERATED BY DEFAULT AS IDENTITY,
  "legacyId"      INTEGER,
  "dateLabel"     VARCHAR(50),
  "date"          DATE,
  "plateNumber"   VARCHAR(20),
  "depot"         VARCHAR(200),
  "sourceTruck"   VARCHAR(200),
  "grossWeight"   INTEGER,
  "tareWeight"    INTEGER,
  "netWeight"     INTEGER,
  "cctvReference" VARCHAR(256),
  "tripId"        BIGINT,
  "createdAt"     TIMESTAMPTZ(6) NOT NULL DEFAULT now(),
  "updatedAt"     TIMESTAMPTZ(6) NOT NULL,
  "operationDate" DATE         NOT NULL DEFAULT CURRENT_DATE,
  CONSTRAINT "TpaInboundLog_pkey" PRIMARY KEY ("operationDate", "id")
) PARTITION BY RANGE ("operationDate");

CREATE INDEX "TpaInboundLog_date_idx" ON "TpaInboundLog" ("date");
CREATE INDEX "TpaInboundLog_plateNumber_idx" ON "TpaInboundLog" ("plateNumber");
CREATE INDEX "TpaInboundLog_tripId_idx" ON "TpaInboundLog" ("tripId");
CREATE INDEX "TpaInboundLog_legacyId_idx" ON "TpaInboundLog" ("legacyId");

-- ---------------------------------------------------------------------------
-- Generate monthly partitions for 2013-01 .. 2026-12 plus a DEFAULT catch-all
-- per table (so out-of-range inserts never fail). Child partitions inherit the
-- parent indexes as local indexes automatically.
-- ---------------------------------------------------------------------------
DO $$
DECLARE
  tbl          TEXT;
  month_start  DATE;
  month_end    DATE;
  part_name    TEXT;
  range_start  CONSTANT DATE := DATE '2013-01-01';
  range_end    CONSTANT DATE := DATE '2027-01-01';
BEGIN
  FOREACH tbl IN ARRAY ARRAY['Trip', 'Haul', 'HaulAssignment', 'TpaInboundLog'] LOOP
    -- DEFAULT partition first (catches anything outside the explicit ranges).
    EXECUTE format(
      'CREATE TABLE IF NOT EXISTS %I PARTITION OF %I DEFAULT',
      lower(tbl) || '_default', tbl
    );

    month_start := range_start;
    WHILE month_start < range_end LOOP
      month_end := (month_start + INTERVAL '1 month')::DATE;
      part_name := format('%s_y%sm%s', lower(tbl), to_char(month_start, 'YYYY'), to_char(month_start, 'MM'));
      EXECUTE format(
        'CREATE TABLE IF NOT EXISTS %I PARTITION OF %I FOR VALUES FROM (%L) TO (%L)',
        part_name, tbl, month_start, month_end
      );
      month_start := month_end;
    END LOOP;
  END LOOP;
END
$$;
