/**
 * Typed accessor for the SAMPLED real legacy transactions baked into
 * demo-transactions.json (latest year, curated demo vehicles/drivers) —
 * AUTO-GENERATED by scripts/generate-demo-transaction-fixtures.ts. Used by
 * prisma/seed.ts so `seed:demo` ships real transaction structure (small volume)
 * with NO MySQL at seed time. The synthetic generator fills the remaining days.
 *
 * Loaded via JSON.parse rather than a TS import: a multi-thousand-row array of
 * enum-typed literals overflows tsc's union representation (TS2590).
 */
import { readFileSync } from 'node:fs';
import { join } from 'node:path';

import type { DayStatus, TripStatus } from '@prisma/client';

export interface DemoTxnDay {
  readonly legacyId: number;
  readonly date: string; // yyyy-MM-dd
  readonly status: DayStatus;
}
export interface DemoTxnHaul {
  readonly legacyId: number;
  readonly dayLegacyId: number;
  readonly vehicleLegacyId: number;
  readonly status: DayStatus;
  readonly notes: string | null;
}
export interface DemoTxnAssignment {
  readonly legacyId: number;
  readonly haulLegacyId: number;
  readonly driverLegacyId: number;
  readonly status: DayStatus;
  readonly departTargetOdometer: number;
  readonly departActualOdometer: number | null;
  readonly returnTargetOdometer: number;
  readonly returnActualOdometer: number | null;
  readonly departTargetTime: string | null;
  readonly departActualTime: string | null;
  readonly returnTargetTime: string | null;
  readonly returnActualTime: string | null;
  readonly notes: string | null;
}
export interface DemoTxnTrip {
  readonly legacyId: number;
  readonly assignmentLegacyId: number;
  readonly routeLegacyId: number | null;
  readonly status: TripStatus;
  readonly name: string;
  readonly targetTime: string | null;
  readonly actualTime: string | null;
  readonly targetOdometer: number;
  readonly actualOdometer: number;
  readonly tareWeight: number;
  readonly grossWeight: number | null;
  readonly netWeight: number | null;
  readonly wasteVolume: number | null;
  readonly fuelRequestedLiters: number | null;
  readonly fuelApprovedLiters: number | null;
  readonly scheduledEntryAt: string | null;
  readonly realizationEntryAt: string | null;
  readonly notes: string | null;
}

export interface DemoTransactions {
  readonly year: number;
  readonly days: readonly DemoTxnDay[];
  readonly hauls: readonly DemoTxnHaul[];
  readonly assignments: readonly DemoTxnAssignment[];
  readonly trips: readonly DemoTxnTrip[];
}

const EMPTY: DemoTransactions = { year: 0, days: [], hauls: [], assignments: [], trips: [] };

function load(): DemoTransactions {
  try {
    return JSON.parse(
      readFileSync(join(__dirname, 'demo-transactions.json'), 'utf-8'),
    ) as DemoTransactions;
  } catch {
    // No fixture committed yet → the seed falls back to fully synthetic transactions.
    return EMPTY;
  }
}

export const DEMO_TRANSACTIONS: DemoTransactions = load();
