/**
 * Cleaned legacy vehicle models (from `kategorikendaraan`, 251 rows). Anomalies
 * normalized on import: 999/≤0 capacity & tare → 0 (unknown), 999/≤0 ratio → 1,
 * 999 wheel-count → 0 (legit 0s kept for non-wheeled equipment), blank brand →
 * "(Tidak Diketahui)". `appLegacyId` → vehicle_type.legacyId; `fuelLegacyId` →
 * the legacy bahanbakar id (resolved to a SWAT fuel by name in the seed).
 */
export interface LegacyVehicleModel {
  readonly legacyId: number;
  readonly appLegacyId: number;
  readonly fuelLegacyId: number;
  readonly brand: string;
  readonly fuelTankCapacity: number;
  readonly normalFuelRatio: number;
  readonly normalTareWeight: number;
  readonly maxNetLoad: number;
  readonly maxNetVolume: number;
  readonly wheelCount: number;
}

export const LEGACY_VEHICLE_MODELS: readonly LegacyVehicleModel[] = [
  {
    legacyId: 1,
    appLegacyId: 1,
    fuelLegacyId: 4,
    brand: 'Hino FF172LA',
    fuelTankCapacity: 0,
    normalFuelRatio: 1,
    normalTareWeight: 0,
    maxNetLoad: 0,
    maxNetVolume: 0,
    wheelCount: 6,
  },
  {
    legacyId: 2,
    appLegacyId: 1,
    fuelLegacyId: 4,
    brand: 'Toyota Ryno BY42/68',
    fuelTankCapacity: 0,
    normalFuelRatio: 1,
    normalTareWeight: 0,
    maxNetLoad: 0,
    maxNetVolume: 0,
    wheelCount: 6,
  },
  {
    legacyId: 3,
    appLegacyId: 2,
    fuelLegacyId: 3,
    brand: 'Toyota Ryno BY42/68',
    fuelTankCapacity: 0,
    normalFuelRatio: 1,
    normalTareWeight: 0,
    maxNetLoad: 0,
    maxNetVolume: 0,
    wheelCount: 6,
  },
  {
    legacyId: 4,
    appLegacyId: 1,
    fuelLegacyId: 4,
    brand: 'Isuzu NKR 66',
    fuelTankCapacity: 0,
    normalFuelRatio: 1,
    normalTareWeight: 0,
    maxNetLoad: 0,
    maxNetVolume: 0,
    wheelCount: 6,
  },
  {
    legacyId: 5,
    appLegacyId: 1,
    fuelLegacyId: 4,
    brand: 'Isuzu NKR 71 STD',
    fuelTankCapacity: 0,
    normalFuelRatio: 1,
    normalTareWeight: 0,
    maxNetLoad: 0,
    maxNetVolume: 0,
    wheelCount: 6,
  },
  {
    legacyId: 6,
    appLegacyId: 1,
    fuelLegacyId: 4,
    brand: 'HINO WU342R DUTRO130HD',
    fuelTankCapacity: 0,
    normalFuelRatio: 1,
    normalTareWeight: 0,
    maxNetLoad: 0,
    maxNetVolume: 0,
    wheelCount: 6,
  },
  {
    legacyId: 7,
    appLegacyId: 1,
    fuelLegacyId: 4,
    brand: 'HINO/FG8JJKB GGJ ( FG235JJ )',
    fuelTankCapacity: 0,
    normalFuelRatio: 1,
    normalTareWeight: 0,
    maxNetLoad: 0,
    maxNetVolume: 0,
    wheelCount: 6,
  },
  {
    legacyId: 8,
    appLegacyId: 3,
    fuelLegacyId: 4,
    brand: 'Isuzu TLD58',
    fuelTankCapacity: 0,
    normalFuelRatio: 1,
    normalTareWeight: 0,
    maxNetLoad: 0,
    maxNetVolume: 0,
    wheelCount: 6,
  },
  {
    legacyId: 9,
    appLegacyId: 3,
    fuelLegacyId: 4,
    brand: 'Toyota Ryno',
    fuelTankCapacity: 0,
    normalFuelRatio: 1,
    normalTareWeight: 0,
    maxNetLoad: 0,
    maxNetVolume: 0,
    wheelCount: 6,
  },
  {
    legacyId: 10,
    appLegacyId: 3,
    fuelLegacyId: 4,
    brand: 'Isuzu NKR 71',
    fuelTankCapacity: 0,
    normalFuelRatio: 1,
    normalTareWeight: 0,
    maxNetLoad: 0,
    maxNetVolume: 0,
    wheelCount: 6,
  },
  {
    legacyId: 11,
    appLegacyId: 3,
    fuelLegacyId: 4,
    brand: 'Hino WU342R DUTRO130 HD',
    fuelTankCapacity: 0,
    normalFuelRatio: 1,
    normalTareWeight: 0,
    maxNetLoad: 0,
    maxNetVolume: 0,
    wheelCount: 6,
  },
  {
    legacyId: 12,
    appLegacyId: 3,
    fuelLegacyId: 4,
    brand: 'Toyota NEW DYNA WU342R TKMQ',
    fuelTankCapacity: 0,
    normalFuelRatio: 1,
    normalTareWeight: 0,
    maxNetLoad: 0,
    maxNetVolume: 0,
    wheelCount: 6,
  },
  {
    legacyId: 13,
    appLegacyId: 3,
    fuelLegacyId: 4,
    brand: 'Isuzu FTR 90 L',
    fuelTankCapacity: 0,
    normalFuelRatio: 1,
    normalTareWeight: 0,
    maxNetLoad: 0,
    maxNetVolume: 0,
    wheelCount: 6,
  },
  {
    legacyId: 14,
    appLegacyId: 4,
    fuelLegacyId: 6,
    brand: 'Mitsubishi F82RH',
    fuelTankCapacity: 0,
    normalFuelRatio: 1,
    normalTareWeight: 0,
    maxNetLoad: 0,
    maxNetVolume: 0,
    wheelCount: 6,
  },
  {
    legacyId: 15,
    appLegacyId: 4,
    fuelLegacyId: 4,
    brand: 'Isuzu NKR 71 STD',
    fuelTankCapacity: 0,
    normalFuelRatio: 1,
    normalTareWeight: 0,
    maxNetLoad: 0,
    maxNetVolume: 0,
    wheelCount: 6,
  },
  {
    legacyId: 16,
    appLegacyId: 4,
    fuelLegacyId: 4,
    brand: 'Isuzu NKR 71 E2',
    fuelTankCapacity: 0,
    normalFuelRatio: 1,
    normalTareWeight: 0,
    maxNetLoad: 0,
    maxNetVolume: 0,
    wheelCount: 6,
  },
  {
    legacyId: 17,
    appLegacyId: 5,
    fuelLegacyId: 4,
    brand: 'Isuzu TLD 58',
    fuelTankCapacity: 0,
    normalFuelRatio: 1,
    normalTareWeight: 0,
    maxNetLoad: 0,
    maxNetVolume: 0,
    wheelCount: 6,
  },
  {
    legacyId: 18,
    appLegacyId: 5,
    fuelLegacyId: 4,
    brand: 'Totota Dyna RBY 43',
    fuelTankCapacity: 0,
    normalFuelRatio: 1,
    normalTareWeight: 0,
    maxNetLoad: 0,
    maxNetVolume: 0,
    wheelCount: 6,
  },
  {
    legacyId: 19,
    appLegacyId: 5,
    fuelLegacyId: 4,
    brand: 'Isuzu NKR 71 HD E2',
    fuelTankCapacity: 0,
    normalFuelRatio: 1,
    normalTareWeight: 0,
    maxNetLoad: 0,
    maxNetVolume: 0,
    wheelCount: 6,
  },
  {
    legacyId: 20,
    appLegacyId: 6,
    fuelLegacyId: 4,
    brand: 'Hino FF173MA',
    fuelTankCapacity: 0,
    normalFuelRatio: 1,
    normalTareWeight: 0,
    maxNetLoad: 0,
    maxNetVolume: 0,
    wheelCount: 6,
  },
  {
    legacyId: 21,
    appLegacyId: 6,
    fuelLegacyId: 4,
    brand: 'Nissan CKA12E/H',
    fuelTankCapacity: 0,
    normalFuelRatio: 1,
    normalTareWeight: 0,
    maxNetLoad: 0,
    maxNetVolume: 0,
    wheelCount: 6,
  },
  {
    legacyId: 22,
    appLegacyId: 6,
    fuelLegacyId: 4,
    brand: 'Isuzu FTR33F',
    fuelTankCapacity: 0,
    normalFuelRatio: 1,
    normalTareWeight: 0,
    maxNetLoad: 0,
    maxNetVolume: 0,
    wheelCount: 6,
  },
  {
    legacyId: 23,
    appLegacyId: 6,
    fuelLegacyId: 4,
    brand: 'Hino FG8JKKB GGJ',
    fuelTankCapacity: 0,
    normalFuelRatio: 1,
    normalTareWeight: 0,
    maxNetLoad: 0,
    maxNetVolume: 0,
    wheelCount: 6,
  },
  {
    legacyId: 24,
    appLegacyId: 6,
    fuelLegacyId: 4,
    brand: 'Isuzu / FTR 90 L',
    fuelTankCapacity: 0,
    normalFuelRatio: 1,
    normalTareWeight: 0,
    maxNetLoad: 0,
    maxNetVolume: 0,
    wheelCount: 6,
  },
  {
    legacyId: 25,
    appLegacyId: 7,
    fuelLegacyId: 3,
    brand: 'Totota Dyna RBY 43',
    fuelTankCapacity: 0,
    normalFuelRatio: 1,
    normalTareWeight: 0,
    maxNetLoad: 0,
    maxNetVolume: 0,
    wheelCount: 6,
  },
  {
    legacyId: 26,
    appLegacyId: 7,
    fuelLegacyId: 4,
    brand: 'Hino FF172LA',
    fuelTankCapacity: 0,
    normalFuelRatio: 1,
    normalTareWeight: 0,
    maxNetLoad: 0,
    maxNetVolume: 0,
    wheelCount: 6,
  },
  {
    legacyId: 27,
    appLegacyId: 8,
    fuelLegacyId: 3,
    brand: 'Isuzu',
    fuelTankCapacity: 0,
    normalFuelRatio: 1,
    normalTareWeight: 0,
    maxNetLoad: 0,
    maxNetVolume: 0,
    wheelCount: 6,
  },
  {
    legacyId: 28,
    appLegacyId: 8,
    fuelLegacyId: 3,
    brand: 'Mercy Bens 700 ATL',
    fuelTankCapacity: 0,
    normalFuelRatio: 1,
    normalTareWeight: 0,
    maxNetLoad: 0,
    maxNetVolume: 0,
    wheelCount: 6,
  },
  {
    legacyId: 29,
    appLegacyId: 8,
    fuelLegacyId: 3,
    brand: 'Isuzu  NKR 71',
    fuelTankCapacity: 0,
    normalFuelRatio: 1,
    normalTareWeight: 0,
    maxNetLoad: 0,
    maxNetVolume: 0,
    wheelCount: 6,
  },
  {
    legacyId: 30,
    appLegacyId: 8,
    fuelLegacyId: 3,
    brand: 'Isuzu NKR 71 HD E2',
    fuelTankCapacity: 0,
    normalFuelRatio: 1,
    normalTareWeight: 0,
    maxNetLoad: 0,
    maxNetVolume: 0,
    wheelCount: 6,
  },
  {
    legacyId: 31,
    appLegacyId: 8,
    fuelLegacyId: 3,
    brand: 'MITS DS FE74HD 4X2 MT',
    fuelTankCapacity: 0,
    normalFuelRatio: 1,
    normalTareWeight: 0,
    maxNetLoad: 0,
    maxNetVolume: 0,
    wheelCount: 6,
  },
  {
    legacyId: 32,
    appLegacyId: 8,
    fuelLegacyId: 4,
    brand: 'HINO WU342R DUTRO 130HD',
    fuelTankCapacity: 0,
    normalFuelRatio: 1,
    normalTareWeight: 0,
    maxNetLoad: 0,
    maxNetVolume: 0,
    wheelCount: 6,
  },
  {
    legacyId: 33,
    appLegacyId: 8,
    fuelLegacyId: 3,
    brand: 'Isuzu NKR 71 E2',
    fuelTankCapacity: 0,
    normalFuelRatio: 1,
    normalTareWeight: 0,
    maxNetLoad: 0,
    maxNetVolume: 0,
    wheelCount: 6,
  },
  {
    legacyId: 34,
    appLegacyId: 8,
    fuelLegacyId: 3,
    brand: 'Mitsubishi DS FE 73B4X2 MT',
    fuelTankCapacity: 0,
    normalFuelRatio: 1,
    normalTareWeight: 0,
    maxNetLoad: 0,
    maxNetVolume: 0,
    wheelCount: 6,
  },
  {
    legacyId: 35,
    appLegacyId: 8,
    fuelLegacyId: 3,
    brand: 'Toyota /Dyna 110 FT',
    fuelTankCapacity: 0,
    normalFuelRatio: 1,
    normalTareWeight: 0,
    maxNetLoad: 0,
    maxNetVolume: 0,
    wheelCount: 6,
  },
  {
    legacyId: 36,
    appLegacyId: 9,
    fuelLegacyId: 4,
    brand: 'Daihatsu V 82RH',
    fuelTankCapacity: 0,
    normalFuelRatio: 1,
    normalTareWeight: 0,
    maxNetLoad: 0,
    maxNetVolume: 0,
    wheelCount: 6,
  },
  {
    legacyId: 37,
    appLegacyId: 9,
    fuelLegacyId: 4,
    brand: 'Isuzu NKR71 E2',
    fuelTankCapacity: 0,
    normalFuelRatio: 1,
    normalTareWeight: 0,
    maxNetLoad: 0,
    maxNetVolume: 0,
    wheelCount: 6,
  },
  {
    legacyId: 38,
    appLegacyId: 10,
    fuelLegacyId: 3,
    brand: 'Mitsubishi FE114',
    fuelTankCapacity: 0,
    normalFuelRatio: 1,
    normalTareWeight: 0,
    maxNetLoad: 0,
    maxNetVolume: 0,
    wheelCount: 6,
  },
  {
    legacyId: 39,
    appLegacyId: 10,
    fuelLegacyId: 3,
    brand: 'Daihatsu V82RH',
    fuelTankCapacity: 0,
    normalFuelRatio: 1,
    normalTareWeight: 0,
    maxNetLoad: 0,
    maxNetVolume: 0,
    wheelCount: 6,
  },
  {
    legacyId: 40,
    appLegacyId: 10,
    fuelLegacyId: 3,
    brand: 'Isuzu',
    fuelTankCapacity: 0,
    normalFuelRatio: 1,
    normalTareWeight: 0,
    maxNetLoad: 0,
    maxNetVolume: 0,
    wheelCount: 6,
  },
  {
    legacyId: 41,
    appLegacyId: 10,
    fuelLegacyId: 3,
    brand: 'Isuzu NKR71',
    fuelTankCapacity: 0,
    normalFuelRatio: 1,
    normalTareWeight: 0,
    maxNetLoad: 0,
    maxNetVolume: 0,
    wheelCount: 6,
  },
  {
    legacyId: 42,
    appLegacyId: 10,
    fuelLegacyId: 3,
    brand: 'Isuzu NKR 71 E2',
    fuelTankCapacity: 0,
    normalFuelRatio: 1,
    normalTareWeight: 0,
    maxNetLoad: 0,
    maxNetVolume: 0,
    wheelCount: 6,
  },
  {
    legacyId: 43,
    appLegacyId: 10,
    fuelLegacyId: 3,
    brand: 'Isuzu NKR 71 HD E2',
    fuelTankCapacity: 0,
    normalFuelRatio: 1,
    normalTareWeight: 0,
    maxNetLoad: 0,
    maxNetVolume: 0,
    wheelCount: 6,
  },
  {
    legacyId: 44,
    appLegacyId: 10,
    fuelLegacyId: 4,
    brand: 'HINO WU342R DUTRO 130HD',
    fuelTankCapacity: 0,
    normalFuelRatio: 1,
    normalTareWeight: 0,
    maxNetLoad: 0,
    maxNetVolume: 0,
    wheelCount: 6,
  },
  {
    legacyId: 45,
    appLegacyId: 11,
    fuelLegacyId: 3,
    brand: 'Toyota Kijang KF50 long',
    fuelTankCapacity: 0,
    normalFuelRatio: 1,
    normalTareWeight: 0,
    maxNetLoad: 0,
    maxNetVolume: 0,
    wheelCount: 4,
  },
  {
    legacyId: 46,
    appLegacyId: 11,
    fuelLegacyId: 2,
    brand: 'Mitsubishi L 300 GP',
    fuelTankCapacity: 0,
    normalFuelRatio: 1,
    normalTareWeight: 0,
    maxNetLoad: 0,
    maxNetVolume: 0,
    wheelCount: 4,
  },
  {
    legacyId: 47,
    appLegacyId: 11,
    fuelLegacyId: 2,
    brand: 'Toyota Kijang KF 50 SPR',
    fuelTankCapacity: 0,
    normalFuelRatio: 1,
    normalTareWeight: 0,
    maxNetLoad: 0,
    maxNetVolume: 0,
    wheelCount: 4,
  },
  {
    legacyId: 48,
    appLegacyId: 11,
    fuelLegacyId: 2,
    brand: 'Mitsubishi L 300 CP',
    fuelTankCapacity: 0,
    normalFuelRatio: 1,
    normalTareWeight: 0,
    maxNetLoad: 0,
    maxNetVolume: 0,
    wheelCount: 4,
  },
  {
    legacyId: 49,
    appLegacyId: 11,
    fuelLegacyId: 2,
    brand: 'Kijang KF52',
    fuelTankCapacity: 0,
    normalFuelRatio: 1,
    normalTareWeight: 0,
    maxNetLoad: 0,
    maxNetVolume: 0,
    wheelCount: 4,
  },
  {
    legacyId: 50,
    appLegacyId: 11,
    fuelLegacyId: 2,
    brand: 'Toyota Kijang KF52 STD',
    fuelTankCapacity: 0,
    normalFuelRatio: 1,
    normalTareWeight: 0,
    maxNetLoad: 0,
    maxNetVolume: 0,
    wheelCount: 4,
  },
  {
    legacyId: 51,
    appLegacyId: 11,
    fuelLegacyId: 3,
    brand: 'Isuzu TBR54PRLC STD',
    fuelTankCapacity: 0,
    normalFuelRatio: 1,
    normalTareWeight: 0,
    maxNetLoad: 0,
    maxNetVolume: 0,
    wheelCount: 4,
  },
  {
    legacyId: 52,
    appLegacyId: 11,
    fuelLegacyId: 3,
    brand: 'Mitsubishi L2002,5L SC',
    fuelTankCapacity: 0,
    normalFuelRatio: 1,
    normalTareWeight: 0,
    maxNetLoad: 0,
    maxNetVolume: 0,
    wheelCount: 4,
  },
  {
    legacyId: 53,
    appLegacyId: 11,
    fuelLegacyId: 3,
    brand: 'Isuzu TBR 54 Turbo',
    fuelTankCapacity: 0,
    normalFuelRatio: 1,
    normalTareWeight: 0,
    maxNetLoad: 0,
    maxNetVolume: 0,
    wheelCount: 4,
  },
  {
    legacyId: 54,
    appLegacyId: 12,
    fuelLegacyId: 3,
    brand: 'Isuzu TBR54PRLC STD',
    fuelTankCapacity: 0,
    normalFuelRatio: 1,
    normalTareWeight: 0,
    maxNetLoad: 0,
    maxNetVolume: 0,
    wheelCount: 4,
  },
  {
    legacyId: 55,
    appLegacyId: 12,
    fuelLegacyId: 3,
    brand: 'Isuzu TBR 54 Turbo',
    fuelTankCapacity: 0,
    normalFuelRatio: 1,
    normalTareWeight: 0,
    maxNetLoad: 0,
    maxNetVolume: 0,
    wheelCount: 4,
  },
  {
    legacyId: 56,
    appLegacyId: 13,
    fuelLegacyId: 3,
    brand: 'Isuzu TBR54 TURBO',
    fuelTankCapacity: 0,
    normalFuelRatio: 1,
    normalTareWeight: 0,
    maxNetLoad: 0,
    maxNetVolume: 0,
    wheelCount: 4,
  },
  {
    legacyId: 57,
    appLegacyId: 14,
    fuelLegacyId: 2,
    brand: 'Mitsubishi L 300',
    fuelTankCapacity: 0,
    normalFuelRatio: 1,
    normalTareWeight: 0,
    maxNetLoad: 0,
    maxNetVolume: 0,
    wheelCount: 4,
  },
  {
    legacyId: 58,
    appLegacyId: 14,
    fuelLegacyId: 2,
    brand: 'Mitsubishi L 300',
    fuelTankCapacity: 0,
    normalFuelRatio: 1,
    normalTareWeight: 0,
    maxNetLoad: 0,
    maxNetVolume: 0,
    wheelCount: 4,
  },
  {
    legacyId: 59,
    appLegacyId: 14,
    fuelLegacyId: 2,
    brand: 'Suzuki ST130',
    fuelTankCapacity: 0,
    normalFuelRatio: 1,
    normalTareWeight: 0,
    maxNetLoad: 0,
    maxNetVolume: 0,
    wheelCount: 4,
  },
  {
    legacyId: 60,
    appLegacyId: 14,
    fuelLegacyId: 2,
    brand: 'Kijang KF42STD',
    fuelTankCapacity: 0,
    normalFuelRatio: 1,
    normalTareWeight: 0,
    maxNetLoad: 0,
    maxNetVolume: 0,
    wheelCount: 4,
  },
  {
    legacyId: 61,
    appLegacyId: 14,
    fuelLegacyId: 2,
    brand: 'Daihatsu 591',
    fuelTankCapacity: 0,
    normalFuelRatio: 1,
    normalTareWeight: 0,
    maxNetLoad: 0,
    maxNetVolume: 0,
    wheelCount: 4,
  },
  {
    legacyId: 62,
    appLegacyId: 14,
    fuelLegacyId: 2,
    brand: 'Toyota Kijang KF42/70',
    fuelTankCapacity: 0,
    normalFuelRatio: 1,
    normalTareWeight: 0,
    maxNetLoad: 0,
    maxNetVolume: 0,
    wheelCount: 4,
  },
  {
    legacyId: 63,
    appLegacyId: 14,
    fuelLegacyId: 2,
    brand: 'Toyota Kijang KF 83 Grand',
    fuelTankCapacity: 0,
    normalFuelRatio: 1,
    normalTareWeight: 0,
    maxNetLoad: 0,
    maxNetVolume: 0,
    wheelCount: 4,
  },
  {
    legacyId: 64,
    appLegacyId: 14,
    fuelLegacyId: 2,
    brand: 'Toyota Kijang KF83SPR',
    fuelTankCapacity: 0,
    normalFuelRatio: 1,
    normalTareWeight: 0,
    maxNetLoad: 0,
    maxNetVolume: 0,
    wheelCount: 4,
  },
  {
    legacyId: 65,
    appLegacyId: 14,
    fuelLegacyId: 3,
    brand: 'Isuzu TBR54PRLC STD',
    fuelTankCapacity: 0,
    normalFuelRatio: 1,
    normalTareWeight: 0,
    maxNetLoad: 0,
    maxNetVolume: 0,
    wheelCount: 4,
  },
  {
    legacyId: 66,
    appLegacyId: 14,
    fuelLegacyId: 3,
    brand: 'Isuzu/TBR 541 LM 25',
    fuelTankCapacity: 0,
    normalFuelRatio: 1,
    normalTareWeight: 0,
    maxNetLoad: 0,
    maxNetVolume: 0,
    wheelCount: 4,
  },
  {
    legacyId: 67,
    appLegacyId: 14,
    fuelLegacyId: 3,
    brand: 'Isuzu /TBR54 PRLC STD',
    fuelTankCapacity: 0,
    normalFuelRatio: 1,
    normalTareWeight: 0,
    maxNetLoad: 0,
    maxNetVolume: 0,
    wheelCount: 4,
  },
  {
    legacyId: 68,
    appLegacyId: 14,
    fuelLegacyId: 2,
    brand: 'Toyota/KJG INNOVA G XW42',
    fuelTankCapacity: 0,
    normalFuelRatio: 1,
    normalTareWeight: 0,
    maxNetLoad: 0,
    maxNetVolume: 0,
    wheelCount: 4,
  },
  {
    legacyId: 69,
    appLegacyId: 15,
    fuelLegacyId: 3,
    brand: 'Daihatsu GT/ F',
    fuelTankCapacity: 0,
    normalFuelRatio: 1,
    normalTareWeight: 0,
    maxNetLoad: 0,
    maxNetVolume: 0,
    wheelCount: 4,
  },
  {
    legacyId: 70,
    appLegacyId: 16,
    fuelLegacyId: 3,
    brand: 'Kendaraan Non-Dinas',
    fuelTankCapacity: 0,
    normalFuelRatio: 1,
    normalTareWeight: 0,
    maxNetLoad: 0,
    maxNetVolume: 0,
    wheelCount: 6,
  },
  {
    legacyId: 71,
    appLegacyId: 11,
    fuelLegacyId: 1,
    brand: 'Daihatsu',
    fuelTankCapacity: 0,
    normalFuelRatio: 1,
    normalTareWeight: 0,
    maxNetLoad: 0,
    maxNetVolume: 0,
    wheelCount: 4,
  },
  {
    legacyId: 72,
    appLegacyId: 17,
    fuelLegacyId: 2,
    brand: 'Belum Tahu',
    fuelTankCapacity: 0,
    normalFuelRatio: 1,
    normalTareWeight: 0,
    maxNetLoad: 0,
    maxNetVolume: 0,
    wheelCount: 3,
  },
  {
    legacyId: 73,
    appLegacyId: 18,
    fuelLegacyId: 3,
    brand: 'Belum Tahu',
    fuelTankCapacity: 0,
    normalFuelRatio: 1,
    normalTareWeight: 0,
    maxNetLoad: 0,
    maxNetVolume: 0,
    wheelCount: 0,
  },
  {
    legacyId: 74,
    appLegacyId: 19,
    fuelLegacyId: 3,
    brand: 'Belum Tahu',
    fuelTankCapacity: 0,
    normalFuelRatio: 1,
    normalTareWeight: 0,
    maxNetLoad: 0,
    maxNetVolume: 0,
    wheelCount: 0,
  },
  {
    legacyId: 75,
    appLegacyId: 20,
    fuelLegacyId: 2,
    brand: 'DRUM',
    fuelTankCapacity: 0,
    normalFuelRatio: 1,
    normalTareWeight: 0,
    maxNetLoad: 0,
    maxNetVolume: 0,
    wheelCount: 0,
  },
  {
    legacyId: 76,
    appLegacyId: 5,
    fuelLegacyId: 4,
    brand: 'Hyno/WU342R Dutro130HP',
    fuelTankCapacity: 0,
    normalFuelRatio: 1,
    normalTareWeight: 0,
    maxNetLoad: 0,
    maxNetVolume: 0,
    wheelCount: 6,
  },
  {
    legacyId: 77,
    appLegacyId: 11,
    fuelLegacyId: 2,
    brand: 'Toyota Hilux',
    fuelTankCapacity: 0,
    normalFuelRatio: 1,
    normalTareWeight: 0,
    maxNetLoad: 0,
    maxNetVolume: 0,
    wheelCount: 0,
  },
  {
    legacyId: 78,
    appLegacyId: 21,
    fuelLegacyId: 3,
    brand: '(Tidak Diketahui)',
    fuelTankCapacity: 0,
    normalFuelRatio: 1,
    normalTareWeight: 0,
    maxNetLoad: 0,
    maxNetVolume: 0,
    wheelCount: 0,
  },
  {
    legacyId: 79,
    appLegacyId: 22,
    fuelLegacyId: 3,
    brand: '(Tidak Diketahui)',
    fuelTankCapacity: 0,
    normalFuelRatio: 1,
    normalTareWeight: 0,
    maxNetLoad: 0,
    maxNetVolume: 0,
    wheelCount: 4,
  },
  {
    legacyId: 80,
    appLegacyId: 19,
    fuelLegacyId: 3,
    brand: '(Tidak Diketahui)',
    fuelTankCapacity: 0,
    normalFuelRatio: 1,
    normalTareWeight: 0,
    maxNetLoad: 0,
    maxNetVolume: 0,
    wheelCount: 0,
  },
  {
    legacyId: 81,
    appLegacyId: 3,
    fuelLegacyId: 3,
    brand: 'Isuzu FTR 90 L1',
    fuelTankCapacity: 0,
    normalFuelRatio: 1,
    normalTareWeight: 0,
    maxNetLoad: 0,
    maxNetVolume: 0,
    wheelCount: 0,
  },
  {
    legacyId: 82,
    appLegacyId: 9,
    fuelLegacyId: 3,
    brand: 'Isuzu NKR71 E21',
    fuelTankCapacity: 0,
    normalFuelRatio: 1,
    normalTareWeight: 0,
    maxNetLoad: 0,
    maxNetVolume: 0,
    wheelCount: 0,
  },
  {
    legacyId: 83,
    appLegacyId: 6,
    fuelLegacyId: 3,
    brand: 'Nissan CKA12E/H1',
    fuelTankCapacity: 0,
    normalFuelRatio: 1,
    normalTareWeight: 0,
    maxNetLoad: 0,
    maxNetVolume: 0,
    wheelCount: 0,
  },
  {
    legacyId: 84,
    appLegacyId: 9,
    fuelLegacyId: 3,
    brand: 'Hino FF172LA',
    fuelTankCapacity: 0,
    normalFuelRatio: 1,
    normalTareWeight: 0,
    maxNetLoad: 0,
    maxNetVolume: 0,
    wheelCount: 0,
  },
  {
    legacyId: 85,
    appLegacyId: 2,
    fuelLegacyId: 4,
    brand: 'MITSUBISHI FM 517 HS',
    fuelTankCapacity: 0,
    normalFuelRatio: 1,
    normalTareWeight: 0,
    maxNetLoad: 0,
    maxNetVolume: 0,
    wheelCount: 0,
  },
  {
    legacyId: 86,
    appLegacyId: 6,
    fuelLegacyId: 4,
    brand: 'MITSUBISHI FM517H',
    fuelTankCapacity: 0,
    normalFuelRatio: 1,
    normalTareWeight: 0,
    maxNetLoad: 0,
    maxNetVolume: 0,
    wheelCount: 0,
  },
  {
    legacyId: 87,
    appLegacyId: 23,
    fuelLegacyId: 3,
    brand: 'Isuzu NKR 71 E2',
    fuelTankCapacity: 0,
    normalFuelRatio: 1,
    normalTareWeight: 0,
    maxNetLoad: 0,
    maxNetVolume: 0,
    wheelCount: 0,
  },
  {
    legacyId: 88,
    appLegacyId: 24,
    fuelLegacyId: 4,
    brand: 'Isuzu TBR54PRLC STD',
    fuelTankCapacity: 0,
    normalFuelRatio: 1,
    normalTareWeight: 0,
    maxNetLoad: 0,
    maxNetVolume: 0,
    wheelCount: 0,
  },
  {
    legacyId: 89,
    appLegacyId: 25,
    fuelLegacyId: 4,
    brand: 'TENNANT',
    fuelTankCapacity: 0,
    normalFuelRatio: 1,
    normalTareWeight: 0,
    maxNetLoad: 0,
    maxNetVolume: 0,
    wheelCount: 0,
  },
  {
    legacyId: 90,
    appLegacyId: 9,
    fuelLegacyId: 3,
    brand: 'Mitsubishi Colt Diesel',
    fuelTankCapacity: 0,
    normalFuelRatio: 1,
    normalTareWeight: 0,
    maxNetLoad: 0,
    maxNetVolume: 0,
    wheelCount: 4,
  },
  {
    legacyId: 91,
    appLegacyId: 10,
    fuelLegacyId: 3,
    brand: 'Hino/WU302RHKMTJ03(130HD)',
    fuelTankCapacity: 0,
    normalFuelRatio: 1,
    normalTareWeight: 0,
    maxNetLoad: 0,
    maxNetVolume: 0,
    wheelCount: 4,
  },
  {
    legacyId: 92,
    appLegacyId: 11,
    fuelLegacyId: 3,
    brand: 'ISUZU TRAGA 2018',
    fuelTankCapacity: 0,
    normalFuelRatio: 1,
    normalTareWeight: 0,
    maxNetLoad: 0,
    maxNetVolume: 0,
    wheelCount: 0,
  },
  {
    legacyId: 93,
    appLegacyId: 1,
    fuelLegacyId: 4,
    brand: 'Merc Benz 1623 R/51 4x2 MT',
    fuelTankCapacity: 0,
    normalFuelRatio: 1,
    normalTareWeight: 0,
    maxNetLoad: 0,
    maxNetVolume: 0,
    wheelCount: 0,
  },
  {
    legacyId: 94,
    appLegacyId: 7,
    fuelLegacyId: 6,
    brand: 'Hino Dytro',
    fuelTankCapacity: 0,
    normalFuelRatio: 1,
    normalTareWeight: 0,
    maxNetLoad: 0,
    maxNetVolume: 0,
    wheelCount: 0,
  },
  {
    legacyId: 95,
    appLegacyId: 26,
    fuelLegacyId: 3,
    brand: 'Forklift Nisan',
    fuelTankCapacity: 0,
    normalFuelRatio: 1,
    normalTareWeight: 0,
    maxNetLoad: 0,
    maxNetVolume: 0,
    wheelCount: 0,
  },
  {
    legacyId: 96,
    appLegacyId: 1,
    fuelLegacyId: 4,
    brand: 'Mitsubishi FM517',
    fuelTankCapacity: 0,
    normalFuelRatio: 1,
    normalTareWeight: 0,
    maxNetLoad: 0,
    maxNetVolume: 0,
    wheelCount: 6,
  },
  {
    legacyId: 97,
    appLegacyId: 3,
    fuelLegacyId: 4,
    brand: 'MITSUBISHI FE114',
    fuelTankCapacity: 0,
    normalFuelRatio: 1,
    normalTareWeight: 0,
    maxNetLoad: 0,
    maxNetVolume: 0,
    wheelCount: 6,
  },
  {
    legacyId: 98,
    appLegacyId: 11,
    fuelLegacyId: 3,
    brand: 'Mitsubishi L300, 5L SC',
    fuelTankCapacity: 0,
    normalFuelRatio: 1,
    normalTareWeight: 0,
    maxNetLoad: 0,
    maxNetVolume: 0,
    wheelCount: 0,
  },
  {
    legacyId: 99,
    appLegacyId: 9,
    fuelLegacyId: 6,
    brand: 'hyno ditro',
    fuelTankCapacity: 0,
    normalFuelRatio: 1,
    normalTareWeight: 0,
    maxNetLoad: 0,
    maxNetVolume: 0,
    wheelCount: 0,
  },
  {
    legacyId: 100,
    appLegacyId: 17,
    fuelLegacyId: 5,
    brand: 'viar',
    fuelTankCapacity: 0,
    normalFuelRatio: 1,
    normalTareWeight: 0,
    maxNetLoad: 0,
    maxNetVolume: 0,
    wheelCount: 3,
  },
  {
    legacyId: 102,
    appLegacyId: 8,
    fuelLegacyId: 6,
    brand: 'Taman Barat',
    fuelTankCapacity: 0,
    normalFuelRatio: 1,
    normalTareWeight: 0,
    maxNetLoad: 0,
    maxNetVolume: 0,
    wheelCount: 6,
  },
  {
    legacyId: 103,
    appLegacyId: 8,
    fuelLegacyId: 6,
    brand: 'Taman Pusat',
    fuelTankCapacity: 0,
    normalFuelRatio: 1,
    normalTareWeight: 0,
    maxNetLoad: 0,
    maxNetVolume: 0,
    wheelCount: 0,
  },
  {
    legacyId: 104,
    appLegacyId: 11,
    fuelLegacyId: 6,
    brand: 'Taman Barat',
    fuelTankCapacity: 0,
    normalFuelRatio: 1,
    normalTareWeight: 0,
    maxNetLoad: 0,
    maxNetVolume: 0,
    wheelCount: 4,
  },
  {
    legacyId: 105,
    appLegacyId: 10,
    fuelLegacyId: 6,
    brand: 'Taman Barat',
    fuelTankCapacity: 0,
    normalFuelRatio: 1,
    normalTareWeight: 0,
    maxNetLoad: 0,
    maxNetVolume: 0,
    wheelCount: 0,
  },
  {
    legacyId: 106,
    appLegacyId: 11,
    fuelLegacyId: 5,
    brand: 'Taman Barat (P)',
    fuelTankCapacity: 0,
    normalFuelRatio: 1,
    normalTareWeight: 0,
    maxNetLoad: 0,
    maxNetVolume: 0,
    wheelCount: 0,
  },
  {
    legacyId: 107,
    appLegacyId: 27,
    fuelLegacyId: 5,
    brand: 'Taman Barat',
    fuelTankCapacity: 0,
    normalFuelRatio: 1,
    normalTareWeight: 0,
    maxNetLoad: 0,
    maxNetVolume: 0,
    wheelCount: 0,
  },
  {
    legacyId: 108,
    appLegacyId: 11,
    fuelLegacyId: 6,
    brand: 'Taman Pusat (D)',
    fuelTankCapacity: 0,
    normalFuelRatio: 1,
    normalTareWeight: 0,
    maxNetLoad: 0,
    maxNetVolume: 0,
    wheelCount: 4,
  },
  {
    legacyId: 109,
    appLegacyId: 10,
    fuelLegacyId: 6,
    brand: 'Taman Pusat (D)',
    fuelTankCapacity: 0,
    normalFuelRatio: 1,
    normalTareWeight: 0,
    maxNetLoad: 0,
    maxNetVolume: 0,
    wheelCount: 6,
  },
  {
    legacyId: 110,
    appLegacyId: 1,
    fuelLegacyId: 4,
    brand: 'UD TRUCK RKE150',
    fuelTankCapacity: 0,
    normalFuelRatio: 1,
    normalTareWeight: 0,
    maxNetLoad: 0,
    maxNetVolume: 0,
    wheelCount: 6,
  },
  {
    legacyId: 111,
    appLegacyId: 14,
    fuelLegacyId: 3,
    brand: 'TOYOTA HIACE',
    fuelTankCapacity: 0,
    normalFuelRatio: 1,
    normalTareWeight: 0,
    maxNetLoad: 0,
    maxNetVolume: 0,
    wheelCount: 0,
  },
  {
    legacyId: 114,
    appLegacyId: 1,
    fuelLegacyId: 4,
    brand: 'Dinas',
    fuelTankCapacity: 0,
    normalFuelRatio: 1,
    normalTareWeight: 0,
    maxNetLoad: 0,
    maxNetVolume: 0,
    wheelCount: 6,
  },
  {
    legacyId: 116,
    appLegacyId: 1,
    fuelLegacyId: 3,
    brand: 'Rekanan',
    fuelTankCapacity: 0,
    normalFuelRatio: 1,
    normalTareWeight: 0,
    maxNetLoad: 0,
    maxNetVolume: 0,
    wheelCount: 0,
  },
  {
    legacyId: 117,
    appLegacyId: 1,
    fuelLegacyId: 3,
    brand: 'Swasta',
    fuelTankCapacity: 0,
    normalFuelRatio: 1,
    normalTareWeight: 0,
    maxNetLoad: 0,
    maxNetVolume: 0,
    wheelCount: 0,
  },
  {
    legacyId: 118,
    appLegacyId: 1,
    fuelLegacyId: 3,
    brand: 'Pelabuhan',
    fuelTankCapacity: 0,
    normalFuelRatio: 1,
    normalTareWeight: 0,
    maxNetLoad: 0,
    maxNetVolume: 0,
    wheelCount: 0,
  },
  {
    legacyId: 119,
    appLegacyId: 1,
    fuelLegacyId: 3,
    brand: 'Pintu Air',
    fuelTankCapacity: 0,
    normalFuelRatio: 1,
    normalTareWeight: 0,
    maxNetLoad: 0,
    maxNetVolume: 0,
    wheelCount: 0,
  },
  {
    legacyId: 120,
    appLegacyId: 2,
    fuelLegacyId: 4,
    brand: 'Dinas',
    fuelTankCapacity: 0,
    normalFuelRatio: 1,
    normalTareWeight: 0,
    maxNetLoad: 0,
    maxNetVolume: 0,
    wheelCount: 0,
  },
  {
    legacyId: 121,
    appLegacyId: 2,
    fuelLegacyId: 3,
    brand: 'Swasta',
    fuelTankCapacity: 0,
    normalFuelRatio: 1,
    normalTareWeight: 0,
    maxNetLoad: 0,
    maxNetVolume: 0,
    wheelCount: 0,
  },
  {
    legacyId: 122,
    appLegacyId: 2,
    fuelLegacyId: 3,
    brand: 'Rekanan',
    fuelTankCapacity: 0,
    normalFuelRatio: 1,
    normalTareWeight: 0,
    maxNetLoad: 0,
    maxNetVolume: 0,
    wheelCount: 0,
  },
  {
    legacyId: 123,
    appLegacyId: 2,
    fuelLegacyId: 3,
    brand: 'Pelabuhan',
    fuelTankCapacity: 0,
    normalFuelRatio: 1,
    normalTareWeight: 0,
    maxNetLoad: 0,
    maxNetVolume: 0,
    wheelCount: 0,
  },
  {
    legacyId: 124,
    appLegacyId: 2,
    fuelLegacyId: 3,
    brand: 'Pintu Air',
    fuelTankCapacity: 0,
    normalFuelRatio: 1,
    normalTareWeight: 0,
    maxNetLoad: 0,
    maxNetVolume: 0,
    wheelCount: 0,
  },
  {
    legacyId: 125,
    appLegacyId: 3,
    fuelLegacyId: 4,
    brand: 'Dinas',
    fuelTankCapacity: 0,
    normalFuelRatio: 1,
    normalTareWeight: 0,
    maxNetLoad: 0,
    maxNetVolume: 0,
    wheelCount: 0,
  },
  {
    legacyId: 126,
    appLegacyId: 3,
    fuelLegacyId: 3,
    brand: 'Rekanan',
    fuelTankCapacity: 0,
    normalFuelRatio: 1,
    normalTareWeight: 0,
    maxNetLoad: 0,
    maxNetVolume: 0,
    wheelCount: 0,
  },
  {
    legacyId: 127,
    appLegacyId: 3,
    fuelLegacyId: 3,
    brand: 'Swasta',
    fuelTankCapacity: 0,
    normalFuelRatio: 1,
    normalTareWeight: 0,
    maxNetLoad: 0,
    maxNetVolume: 0,
    wheelCount: 0,
  },
  {
    legacyId: 128,
    appLegacyId: 3,
    fuelLegacyId: 3,
    brand: 'Pelabuhan',
    fuelTankCapacity: 0,
    normalFuelRatio: 1,
    normalTareWeight: 0,
    maxNetLoad: 0,
    maxNetVolume: 0,
    wheelCount: 0,
  },
  {
    legacyId: 129,
    appLegacyId: 3,
    fuelLegacyId: 3,
    brand: 'Pintu Air',
    fuelTankCapacity: 0,
    normalFuelRatio: 1,
    normalTareWeight: 0,
    maxNetLoad: 0,
    maxNetVolume: 0,
    wheelCount: 0,
  },
  {
    legacyId: 130,
    appLegacyId: 4,
    fuelLegacyId: 4,
    brand: 'Dinas',
    fuelTankCapacity: 0,
    normalFuelRatio: 1,
    normalTareWeight: 0,
    maxNetLoad: 0,
    maxNetVolume: 0,
    wheelCount: 0,
  },
  {
    legacyId: 132,
    appLegacyId: 4,
    fuelLegacyId: 3,
    brand: 'Rekanan',
    fuelTankCapacity: 0,
    normalFuelRatio: 1,
    normalTareWeight: 0,
    maxNetLoad: 0,
    maxNetVolume: 0,
    wheelCount: 0,
  },
  {
    legacyId: 133,
    appLegacyId: 4,
    fuelLegacyId: 3,
    brand: 'Swasta',
    fuelTankCapacity: 0,
    normalFuelRatio: 1,
    normalTareWeight: 0,
    maxNetLoad: 0,
    maxNetVolume: 0,
    wheelCount: 0,
  },
  {
    legacyId: 134,
    appLegacyId: 4,
    fuelLegacyId: 3,
    brand: 'Pelabuhan',
    fuelTankCapacity: 0,
    normalFuelRatio: 1,
    normalTareWeight: 0,
    maxNetLoad: 0,
    maxNetVolume: 0,
    wheelCount: 0,
  },
  {
    legacyId: 135,
    appLegacyId: 4,
    fuelLegacyId: 3,
    brand: 'Pintu Air',
    fuelTankCapacity: 0,
    normalFuelRatio: 1,
    normalTareWeight: 0,
    maxNetLoad: 0,
    maxNetVolume: 0,
    wheelCount: 0,
  },
  {
    legacyId: 136,
    appLegacyId: 5,
    fuelLegacyId: 4,
    brand: 'Dinas',
    fuelTankCapacity: 0,
    normalFuelRatio: 1,
    normalTareWeight: 0,
    maxNetLoad: 0,
    maxNetVolume: 0,
    wheelCount: 0,
  },
  {
    legacyId: 137,
    appLegacyId: 5,
    fuelLegacyId: 3,
    brand: 'Rekanan',
    fuelTankCapacity: 0,
    normalFuelRatio: 1,
    normalTareWeight: 0,
    maxNetLoad: 0,
    maxNetVolume: 0,
    wheelCount: 0,
  },
  {
    legacyId: 138,
    appLegacyId: 5,
    fuelLegacyId: 3,
    brand: 'Swasta',
    fuelTankCapacity: 0,
    normalFuelRatio: 1,
    normalTareWeight: 0,
    maxNetLoad: 0,
    maxNetVolume: 0,
    wheelCount: 0,
  },
  {
    legacyId: 139,
    appLegacyId: 5,
    fuelLegacyId: 3,
    brand: 'Pelabuhan',
    fuelTankCapacity: 0,
    normalFuelRatio: 1,
    normalTareWeight: 0,
    maxNetLoad: 0,
    maxNetVolume: 0,
    wheelCount: 0,
  },
  {
    legacyId: 140,
    appLegacyId: 5,
    fuelLegacyId: 3,
    brand: 'Pintu Air',
    fuelTankCapacity: 0,
    normalFuelRatio: 1,
    normalTareWeight: 0,
    maxNetLoad: 0,
    maxNetVolume: 0,
    wheelCount: 0,
  },
  {
    legacyId: 141,
    appLegacyId: 6,
    fuelLegacyId: 4,
    brand: 'Dinas',
    fuelTankCapacity: 0,
    normalFuelRatio: 1,
    normalTareWeight: 0,
    maxNetLoad: 0,
    maxNetVolume: 0,
    wheelCount: 0,
  },
  {
    legacyId: 142,
    appLegacyId: 6,
    fuelLegacyId: 3,
    brand: 'Rekanan',
    fuelTankCapacity: 0,
    normalFuelRatio: 1,
    normalTareWeight: 0,
    maxNetLoad: 0,
    maxNetVolume: 0,
    wheelCount: 0,
  },
  {
    legacyId: 143,
    appLegacyId: 6,
    fuelLegacyId: 3,
    brand: 'Swasta',
    fuelTankCapacity: 0,
    normalFuelRatio: 1,
    normalTareWeight: 0,
    maxNetLoad: 0,
    maxNetVolume: 0,
    wheelCount: 0,
  },
  {
    legacyId: 144,
    appLegacyId: 6,
    fuelLegacyId: 3,
    brand: 'Pelabuhan',
    fuelTankCapacity: 0,
    normalFuelRatio: 1,
    normalTareWeight: 0,
    maxNetLoad: 0,
    maxNetVolume: 0,
    wheelCount: 0,
  },
  {
    legacyId: 145,
    appLegacyId: 6,
    fuelLegacyId: 3,
    brand: 'Pintu Air',
    fuelTankCapacity: 0,
    normalFuelRatio: 1,
    normalTareWeight: 0,
    maxNetLoad: 0,
    maxNetVolume: 0,
    wheelCount: 0,
  },
  {
    legacyId: 146,
    appLegacyId: 7,
    fuelLegacyId: 4,
    brand: 'Dinas',
    fuelTankCapacity: 0,
    normalFuelRatio: 1,
    normalTareWeight: 0,
    maxNetLoad: 0,
    maxNetVolume: 0,
    wheelCount: 0,
  },
  {
    legacyId: 147,
    appLegacyId: 7,
    fuelLegacyId: 3,
    brand: 'Rekanan',
    fuelTankCapacity: 0,
    normalFuelRatio: 1,
    normalTareWeight: 0,
    maxNetLoad: 0,
    maxNetVolume: 0,
    wheelCount: 0,
  },
  {
    legacyId: 148,
    appLegacyId: 7,
    fuelLegacyId: 3,
    brand: 'Swasta',
    fuelTankCapacity: 0,
    normalFuelRatio: 1,
    normalTareWeight: 0,
    maxNetLoad: 0,
    maxNetVolume: 0,
    wheelCount: 0,
  },
  {
    legacyId: 149,
    appLegacyId: 7,
    fuelLegacyId: 3,
    brand: 'Pelabuhan',
    fuelTankCapacity: 0,
    normalFuelRatio: 1,
    normalTareWeight: 0,
    maxNetLoad: 0,
    maxNetVolume: 0,
    wheelCount: 0,
  },
  {
    legacyId: 150,
    appLegacyId: 7,
    fuelLegacyId: 3,
    brand: 'Pintu Air',
    fuelTankCapacity: 0,
    normalFuelRatio: 1,
    normalTareWeight: 0,
    maxNetLoad: 0,
    maxNetVolume: 0,
    wheelCount: 0,
  },
  {
    legacyId: 151,
    appLegacyId: 8,
    fuelLegacyId: 4,
    brand: 'Dinas',
    fuelTankCapacity: 0,
    normalFuelRatio: 1,
    normalTareWeight: 0,
    maxNetLoad: 0,
    maxNetVolume: 0,
    wheelCount: 0,
  },
  {
    legacyId: 152,
    appLegacyId: 8,
    fuelLegacyId: 3,
    brand: 'Rekanan',
    fuelTankCapacity: 0,
    normalFuelRatio: 1,
    normalTareWeight: 0,
    maxNetLoad: 0,
    maxNetVolume: 0,
    wheelCount: 0,
  },
  {
    legacyId: 153,
    appLegacyId: 8,
    fuelLegacyId: 3,
    brand: 'Swasta',
    fuelTankCapacity: 0,
    normalFuelRatio: 1,
    normalTareWeight: 0,
    maxNetLoad: 0,
    maxNetVolume: 0,
    wheelCount: 0,
  },
  {
    legacyId: 154,
    appLegacyId: 8,
    fuelLegacyId: 3,
    brand: 'Pelabuhan',
    fuelTankCapacity: 0,
    normalFuelRatio: 1,
    normalTareWeight: 0,
    maxNetLoad: 0,
    maxNetVolume: 0,
    wheelCount: 0,
  },
  {
    legacyId: 155,
    appLegacyId: 8,
    fuelLegacyId: 3,
    brand: 'Pintu Air',
    fuelTankCapacity: 0,
    normalFuelRatio: 1,
    normalTareWeight: 0,
    maxNetLoad: 0,
    maxNetVolume: 0,
    wheelCount: 0,
  },
  {
    legacyId: 156,
    appLegacyId: 9,
    fuelLegacyId: 4,
    brand: 'Dinas',
    fuelTankCapacity: 0,
    normalFuelRatio: 1,
    normalTareWeight: 0,
    maxNetLoad: 0,
    maxNetVolume: 0,
    wheelCount: 0,
  },
  {
    legacyId: 157,
    appLegacyId: 9,
    fuelLegacyId: 3,
    brand: 'Rekanan',
    fuelTankCapacity: 0,
    normalFuelRatio: 1,
    normalTareWeight: 0,
    maxNetLoad: 0,
    maxNetVolume: 0,
    wheelCount: 0,
  },
  {
    legacyId: 158,
    appLegacyId: 9,
    fuelLegacyId: 3,
    brand: 'Swasta',
    fuelTankCapacity: 0,
    normalFuelRatio: 1,
    normalTareWeight: 0,
    maxNetLoad: 0,
    maxNetVolume: 0,
    wheelCount: 0,
  },
  {
    legacyId: 159,
    appLegacyId: 9,
    fuelLegacyId: 3,
    brand: 'Pelabuhan',
    fuelTankCapacity: 0,
    normalFuelRatio: 1,
    normalTareWeight: 0,
    maxNetLoad: 0,
    maxNetVolume: 0,
    wheelCount: 0,
  },
  {
    legacyId: 160,
    appLegacyId: 9,
    fuelLegacyId: 3,
    brand: 'Pintu Air',
    fuelTankCapacity: 0,
    normalFuelRatio: 1,
    normalTareWeight: 0,
    maxNetLoad: 0,
    maxNetVolume: 0,
    wheelCount: 0,
  },
  {
    legacyId: 161,
    appLegacyId: 10,
    fuelLegacyId: 4,
    brand: 'Dinas',
    fuelTankCapacity: 0,
    normalFuelRatio: 1,
    normalTareWeight: 0,
    maxNetLoad: 0,
    maxNetVolume: 0,
    wheelCount: 0,
  },
  {
    legacyId: 162,
    appLegacyId: 10,
    fuelLegacyId: 3,
    brand: 'Rekanan',
    fuelTankCapacity: 0,
    normalFuelRatio: 1,
    normalTareWeight: 0,
    maxNetLoad: 0,
    maxNetVolume: 0,
    wheelCount: 0,
  },
  {
    legacyId: 163,
    appLegacyId: 10,
    fuelLegacyId: 3,
    brand: 'Swasta',
    fuelTankCapacity: 0,
    normalFuelRatio: 1,
    normalTareWeight: 0,
    maxNetLoad: 0,
    maxNetVolume: 0,
    wheelCount: 0,
  },
  {
    legacyId: 164,
    appLegacyId: 10,
    fuelLegacyId: 3,
    brand: 'Pelabuhan',
    fuelTankCapacity: 0,
    normalFuelRatio: 1,
    normalTareWeight: 0,
    maxNetLoad: 0,
    maxNetVolume: 0,
    wheelCount: 0,
  },
  {
    legacyId: 165,
    appLegacyId: 10,
    fuelLegacyId: 3,
    brand: 'Pintu Air',
    fuelTankCapacity: 0,
    normalFuelRatio: 1,
    normalTareWeight: 0,
    maxNetLoad: 0,
    maxNetVolume: 0,
    wheelCount: 0,
  },
  {
    legacyId: 166,
    appLegacyId: 11,
    fuelLegacyId: 4,
    brand: 'Dinas',
    fuelTankCapacity: 0,
    normalFuelRatio: 1,
    normalTareWeight: 0,
    maxNetLoad: 0,
    maxNetVolume: 0,
    wheelCount: 0,
  },
  {
    legacyId: 167,
    appLegacyId: 11,
    fuelLegacyId: 3,
    brand: 'Rekanan',
    fuelTankCapacity: 0,
    normalFuelRatio: 1,
    normalTareWeight: 0,
    maxNetLoad: 0,
    maxNetVolume: 0,
    wheelCount: 0,
  },
  {
    legacyId: 168,
    appLegacyId: 11,
    fuelLegacyId: 3,
    brand: 'Swasta',
    fuelTankCapacity: 0,
    normalFuelRatio: 1,
    normalTareWeight: 0,
    maxNetLoad: 0,
    maxNetVolume: 0,
    wheelCount: 0,
  },
  {
    legacyId: 169,
    appLegacyId: 11,
    fuelLegacyId: 3,
    brand: 'Pelabuhan',
    fuelTankCapacity: 0,
    normalFuelRatio: 1,
    normalTareWeight: 0,
    maxNetLoad: 0,
    maxNetVolume: 0,
    wheelCount: 0,
  },
  {
    legacyId: 170,
    appLegacyId: 11,
    fuelLegacyId: 3,
    brand: 'Pintu Air',
    fuelTankCapacity: 0,
    normalFuelRatio: 1,
    normalTareWeight: 0,
    maxNetLoad: 0,
    maxNetVolume: 0,
    wheelCount: 0,
  },
  {
    legacyId: 171,
    appLegacyId: 12,
    fuelLegacyId: 4,
    brand: 'Dinas',
    fuelTankCapacity: 0,
    normalFuelRatio: 1,
    normalTareWeight: 0,
    maxNetLoad: 0,
    maxNetVolume: 0,
    wheelCount: 0,
  },
  {
    legacyId: 172,
    appLegacyId: 12,
    fuelLegacyId: 3,
    brand: 'Rekanan',
    fuelTankCapacity: 0,
    normalFuelRatio: 1,
    normalTareWeight: 0,
    maxNetLoad: 0,
    maxNetVolume: 0,
    wheelCount: 0,
  },
  {
    legacyId: 173,
    appLegacyId: 12,
    fuelLegacyId: 3,
    brand: 'Swasta',
    fuelTankCapacity: 0,
    normalFuelRatio: 1,
    normalTareWeight: 0,
    maxNetLoad: 0,
    maxNetVolume: 0,
    wheelCount: 0,
  },
  {
    legacyId: 174,
    appLegacyId: 12,
    fuelLegacyId: 3,
    brand: 'Pelabuhan',
    fuelTankCapacity: 0,
    normalFuelRatio: 1,
    normalTareWeight: 0,
    maxNetLoad: 0,
    maxNetVolume: 0,
    wheelCount: 0,
  },
  {
    legacyId: 175,
    appLegacyId: 12,
    fuelLegacyId: 3,
    brand: 'Pintu Air',
    fuelTankCapacity: 0,
    normalFuelRatio: 1,
    normalTareWeight: 0,
    maxNetLoad: 0,
    maxNetVolume: 0,
    wheelCount: 0,
  },
  {
    legacyId: 176,
    appLegacyId: 13,
    fuelLegacyId: 4,
    brand: 'Dinas',
    fuelTankCapacity: 0,
    normalFuelRatio: 1,
    normalTareWeight: 0,
    maxNetLoad: 0,
    maxNetVolume: 0,
    wheelCount: 0,
  },
  {
    legacyId: 177,
    appLegacyId: 13,
    fuelLegacyId: 3,
    brand: 'Rekanan',
    fuelTankCapacity: 0,
    normalFuelRatio: 1,
    normalTareWeight: 0,
    maxNetLoad: 0,
    maxNetVolume: 0,
    wheelCount: 0,
  },
  {
    legacyId: 178,
    appLegacyId: 13,
    fuelLegacyId: 3,
    brand: 'Swasta',
    fuelTankCapacity: 0,
    normalFuelRatio: 1,
    normalTareWeight: 0,
    maxNetLoad: 0,
    maxNetVolume: 0,
    wheelCount: 0,
  },
  {
    legacyId: 179,
    appLegacyId: 13,
    fuelLegacyId: 3,
    brand: 'Pelabuhan',
    fuelTankCapacity: 0,
    normalFuelRatio: 1,
    normalTareWeight: 0,
    maxNetLoad: 0,
    maxNetVolume: 0,
    wheelCount: 0,
  },
  {
    legacyId: 180,
    appLegacyId: 13,
    fuelLegacyId: 3,
    brand: 'Pintu Air',
    fuelTankCapacity: 0,
    normalFuelRatio: 1,
    normalTareWeight: 0,
    maxNetLoad: 0,
    maxNetVolume: 0,
    wheelCount: 0,
  },
  {
    legacyId: 181,
    appLegacyId: 14,
    fuelLegacyId: 4,
    brand: 'Dinas',
    fuelTankCapacity: 0,
    normalFuelRatio: 1,
    normalTareWeight: 0,
    maxNetLoad: 0,
    maxNetVolume: 0,
    wheelCount: 0,
  },
  {
    legacyId: 182,
    appLegacyId: 14,
    fuelLegacyId: 3,
    brand: 'Rekanan',
    fuelTankCapacity: 0,
    normalFuelRatio: 1,
    normalTareWeight: 0,
    maxNetLoad: 0,
    maxNetVolume: 0,
    wheelCount: 0,
  },
  {
    legacyId: 183,
    appLegacyId: 14,
    fuelLegacyId: 3,
    brand: 'Swasta',
    fuelTankCapacity: 0,
    normalFuelRatio: 1,
    normalTareWeight: 0,
    maxNetLoad: 0,
    maxNetVolume: 0,
    wheelCount: 0,
  },
  {
    legacyId: 184,
    appLegacyId: 14,
    fuelLegacyId: 3,
    brand: 'Pelabuhan',
    fuelTankCapacity: 0,
    normalFuelRatio: 1,
    normalTareWeight: 0,
    maxNetLoad: 0,
    maxNetVolume: 0,
    wheelCount: 0,
  },
  {
    legacyId: 185,
    appLegacyId: 14,
    fuelLegacyId: 3,
    brand: 'Pintu Air',
    fuelTankCapacity: 0,
    normalFuelRatio: 1,
    normalTareWeight: 0,
    maxNetLoad: 0,
    maxNetVolume: 0,
    wheelCount: 0,
  },
  {
    legacyId: 186,
    appLegacyId: 15,
    fuelLegacyId: 4,
    brand: 'Dinas',
    fuelTankCapacity: 0,
    normalFuelRatio: 1,
    normalTareWeight: 0,
    maxNetLoad: 0,
    maxNetVolume: 0,
    wheelCount: 0,
  },
  {
    legacyId: 187,
    appLegacyId: 15,
    fuelLegacyId: 3,
    brand: 'Rekanan',
    fuelTankCapacity: 0,
    normalFuelRatio: 1,
    normalTareWeight: 0,
    maxNetLoad: 0,
    maxNetVolume: 0,
    wheelCount: 0,
  },
  {
    legacyId: 188,
    appLegacyId: 15,
    fuelLegacyId: 3,
    brand: 'Swasta',
    fuelTankCapacity: 0,
    normalFuelRatio: 1,
    normalTareWeight: 0,
    maxNetLoad: 0,
    maxNetVolume: 0,
    wheelCount: 0,
  },
  {
    legacyId: 189,
    appLegacyId: 15,
    fuelLegacyId: 3,
    brand: 'Pelabuhan',
    fuelTankCapacity: 0,
    normalFuelRatio: 1,
    normalTareWeight: 0,
    maxNetLoad: 0,
    maxNetVolume: 0,
    wheelCount: 0,
  },
  {
    legacyId: 190,
    appLegacyId: 15,
    fuelLegacyId: 3,
    brand: 'Pintu Air',
    fuelTankCapacity: 0,
    normalFuelRatio: 1,
    normalTareWeight: 0,
    maxNetLoad: 0,
    maxNetVolume: 0,
    wheelCount: 0,
  },
  {
    legacyId: 191,
    appLegacyId: 16,
    fuelLegacyId: 4,
    brand: 'Dinas',
    fuelTankCapacity: 0,
    normalFuelRatio: 1,
    normalTareWeight: 0,
    maxNetLoad: 0,
    maxNetVolume: 0,
    wheelCount: 0,
  },
  {
    legacyId: 192,
    appLegacyId: 16,
    fuelLegacyId: 3,
    brand: 'Rekanan',
    fuelTankCapacity: 0,
    normalFuelRatio: 1,
    normalTareWeight: 0,
    maxNetLoad: 0,
    maxNetVolume: 0,
    wheelCount: 0,
  },
  {
    legacyId: 193,
    appLegacyId: 16,
    fuelLegacyId: 3,
    brand: 'Swasta',
    fuelTankCapacity: 0,
    normalFuelRatio: 1,
    normalTareWeight: 0,
    maxNetLoad: 0,
    maxNetVolume: 0,
    wheelCount: 0,
  },
  {
    legacyId: 194,
    appLegacyId: 16,
    fuelLegacyId: 3,
    brand: 'Pelabuhan',
    fuelTankCapacity: 0,
    normalFuelRatio: 1,
    normalTareWeight: 0,
    maxNetLoad: 0,
    maxNetVolume: 0,
    wheelCount: 0,
  },
  {
    legacyId: 195,
    appLegacyId: 16,
    fuelLegacyId: 3,
    brand: 'Pintu Air',
    fuelTankCapacity: 0,
    normalFuelRatio: 1,
    normalTareWeight: 0,
    maxNetLoad: 0,
    maxNetVolume: 0,
    wheelCount: 0,
  },
  {
    legacyId: 196,
    appLegacyId: 17,
    fuelLegacyId: 4,
    brand: 'Dinas',
    fuelTankCapacity: 0,
    normalFuelRatio: 1,
    normalTareWeight: 0,
    maxNetLoad: 0,
    maxNetVolume: 0,
    wheelCount: 0,
  },
  {
    legacyId: 197,
    appLegacyId: 17,
    fuelLegacyId: 3,
    brand: 'Rekanan',
    fuelTankCapacity: 0,
    normalFuelRatio: 1,
    normalTareWeight: 0,
    maxNetLoad: 0,
    maxNetVolume: 0,
    wheelCount: 0,
  },
  {
    legacyId: 198,
    appLegacyId: 17,
    fuelLegacyId: 3,
    brand: 'Swasta',
    fuelTankCapacity: 0,
    normalFuelRatio: 1,
    normalTareWeight: 0,
    maxNetLoad: 0,
    maxNetVolume: 0,
    wheelCount: 0,
  },
  {
    legacyId: 199,
    appLegacyId: 17,
    fuelLegacyId: 3,
    brand: 'Pelabuhan',
    fuelTankCapacity: 0,
    normalFuelRatio: 1,
    normalTareWeight: 0,
    maxNetLoad: 0,
    maxNetVolume: 0,
    wheelCount: 0,
  },
  {
    legacyId: 200,
    appLegacyId: 17,
    fuelLegacyId: 3,
    brand: 'Pintu Air',
    fuelTankCapacity: 0,
    normalFuelRatio: 1,
    normalTareWeight: 0,
    maxNetLoad: 0,
    maxNetVolume: 0,
    wheelCount: 0,
  },
  {
    legacyId: 201,
    appLegacyId: 18,
    fuelLegacyId: 4,
    brand: 'Dinas',
    fuelTankCapacity: 0,
    normalFuelRatio: 1,
    normalTareWeight: 0,
    maxNetLoad: 0,
    maxNetVolume: 0,
    wheelCount: 0,
  },
  {
    legacyId: 202,
    appLegacyId: 18,
    fuelLegacyId: 3,
    brand: 'Rekanan',
    fuelTankCapacity: 0,
    normalFuelRatio: 1,
    normalTareWeight: 0,
    maxNetLoad: 0,
    maxNetVolume: 0,
    wheelCount: 0,
  },
  {
    legacyId: 203,
    appLegacyId: 18,
    fuelLegacyId: 3,
    brand: 'Swasta',
    fuelTankCapacity: 0,
    normalFuelRatio: 1,
    normalTareWeight: 0,
    maxNetLoad: 0,
    maxNetVolume: 0,
    wheelCount: 0,
  },
  {
    legacyId: 204,
    appLegacyId: 18,
    fuelLegacyId: 3,
    brand: 'Pelabuhan',
    fuelTankCapacity: 0,
    normalFuelRatio: 1,
    normalTareWeight: 0,
    maxNetLoad: 0,
    maxNetVolume: 0,
    wheelCount: 0,
  },
  {
    legacyId: 205,
    appLegacyId: 18,
    fuelLegacyId: 3,
    brand: 'Pintu Air',
    fuelTankCapacity: 0,
    normalFuelRatio: 1,
    normalTareWeight: 0,
    maxNetLoad: 0,
    maxNetVolume: 0,
    wheelCount: 0,
  },
  {
    legacyId: 206,
    appLegacyId: 19,
    fuelLegacyId: 4,
    brand: 'Dinas',
    fuelTankCapacity: 0,
    normalFuelRatio: 1,
    normalTareWeight: 0,
    maxNetLoad: 0,
    maxNetVolume: 0,
    wheelCount: 0,
  },
  {
    legacyId: 207,
    appLegacyId: 19,
    fuelLegacyId: 3,
    brand: 'Rekanan',
    fuelTankCapacity: 0,
    normalFuelRatio: 1,
    normalTareWeight: 0,
    maxNetLoad: 0,
    maxNetVolume: 0,
    wheelCount: 0,
  },
  {
    legacyId: 208,
    appLegacyId: 19,
    fuelLegacyId: 3,
    brand: 'Swasta',
    fuelTankCapacity: 0,
    normalFuelRatio: 1,
    normalTareWeight: 0,
    maxNetLoad: 0,
    maxNetVolume: 0,
    wheelCount: 0,
  },
  {
    legacyId: 209,
    appLegacyId: 19,
    fuelLegacyId: 3,
    brand: 'Pelabuhan',
    fuelTankCapacity: 0,
    normalFuelRatio: 1,
    normalTareWeight: 0,
    maxNetLoad: 0,
    maxNetVolume: 0,
    wheelCount: 0,
  },
  {
    legacyId: 210,
    appLegacyId: 19,
    fuelLegacyId: 3,
    brand: 'Pintu Air',
    fuelTankCapacity: 0,
    normalFuelRatio: 1,
    normalTareWeight: 0,
    maxNetLoad: 0,
    maxNetVolume: 0,
    wheelCount: 0,
  },
  {
    legacyId: 211,
    appLegacyId: 20,
    fuelLegacyId: 4,
    brand: 'Dinas',
    fuelTankCapacity: 0,
    normalFuelRatio: 1,
    normalTareWeight: 0,
    maxNetLoad: 0,
    maxNetVolume: 0,
    wheelCount: 0,
  },
  {
    legacyId: 212,
    appLegacyId: 20,
    fuelLegacyId: 3,
    brand: 'Rekanan',
    fuelTankCapacity: 0,
    normalFuelRatio: 1,
    normalTareWeight: 0,
    maxNetLoad: 0,
    maxNetVolume: 0,
    wheelCount: 0,
  },
  {
    legacyId: 213,
    appLegacyId: 20,
    fuelLegacyId: 3,
    brand: 'Swasta',
    fuelTankCapacity: 0,
    normalFuelRatio: 1,
    normalTareWeight: 0,
    maxNetLoad: 0,
    maxNetVolume: 0,
    wheelCount: 0,
  },
  {
    legacyId: 214,
    appLegacyId: 20,
    fuelLegacyId: 3,
    brand: 'Pelabuhan',
    fuelTankCapacity: 0,
    normalFuelRatio: 1,
    normalTareWeight: 0,
    maxNetLoad: 0,
    maxNetVolume: 0,
    wheelCount: 0,
  },
  {
    legacyId: 215,
    appLegacyId: 20,
    fuelLegacyId: 3,
    brand: 'Pintu Air',
    fuelTankCapacity: 0,
    normalFuelRatio: 1,
    normalTareWeight: 0,
    maxNetLoad: 0,
    maxNetVolume: 0,
    wheelCount: 0,
  },
  {
    legacyId: 216,
    appLegacyId: 21,
    fuelLegacyId: 4,
    brand: 'Dinas',
    fuelTankCapacity: 0,
    normalFuelRatio: 1,
    normalTareWeight: 0,
    maxNetLoad: 0,
    maxNetVolume: 0,
    wheelCount: 0,
  },
  {
    legacyId: 217,
    appLegacyId: 21,
    fuelLegacyId: 3,
    brand: 'Rekanan',
    fuelTankCapacity: 0,
    normalFuelRatio: 1,
    normalTareWeight: 0,
    maxNetLoad: 0,
    maxNetVolume: 0,
    wheelCount: 0,
  },
  {
    legacyId: 218,
    appLegacyId: 21,
    fuelLegacyId: 3,
    brand: 'Swasta',
    fuelTankCapacity: 0,
    normalFuelRatio: 1,
    normalTareWeight: 0,
    maxNetLoad: 0,
    maxNetVolume: 0,
    wheelCount: 0,
  },
  {
    legacyId: 219,
    appLegacyId: 21,
    fuelLegacyId: 3,
    brand: 'Pelabuhan',
    fuelTankCapacity: 0,
    normalFuelRatio: 1,
    normalTareWeight: 0,
    maxNetLoad: 0,
    maxNetVolume: 0,
    wheelCount: 0,
  },
  {
    legacyId: 220,
    appLegacyId: 21,
    fuelLegacyId: 3,
    brand: 'Pintu Air',
    fuelTankCapacity: 0,
    normalFuelRatio: 1,
    normalTareWeight: 0,
    maxNetLoad: 0,
    maxNetVolume: 0,
    wheelCount: 0,
  },
  {
    legacyId: 221,
    appLegacyId: 22,
    fuelLegacyId: 4,
    brand: 'Dinas',
    fuelTankCapacity: 0,
    normalFuelRatio: 1,
    normalTareWeight: 0,
    maxNetLoad: 0,
    maxNetVolume: 0,
    wheelCount: 0,
  },
  {
    legacyId: 222,
    appLegacyId: 22,
    fuelLegacyId: 3,
    brand: 'Rekanan',
    fuelTankCapacity: 0,
    normalFuelRatio: 1,
    normalTareWeight: 0,
    maxNetLoad: 0,
    maxNetVolume: 0,
    wheelCount: 0,
  },
  {
    legacyId: 223,
    appLegacyId: 22,
    fuelLegacyId: 3,
    brand: 'Swasta',
    fuelTankCapacity: 0,
    normalFuelRatio: 1,
    normalTareWeight: 0,
    maxNetLoad: 0,
    maxNetVolume: 0,
    wheelCount: 0,
  },
  {
    legacyId: 224,
    appLegacyId: 22,
    fuelLegacyId: 3,
    brand: 'Pelabuhan',
    fuelTankCapacity: 0,
    normalFuelRatio: 1,
    normalTareWeight: 0,
    maxNetLoad: 0,
    maxNetVolume: 0,
    wheelCount: 0,
  },
  {
    legacyId: 225,
    appLegacyId: 22,
    fuelLegacyId: 3,
    brand: 'Pintu Air',
    fuelTankCapacity: 0,
    normalFuelRatio: 1,
    normalTareWeight: 0,
    maxNetLoad: 0,
    maxNetVolume: 0,
    wheelCount: 0,
  },
  {
    legacyId: 226,
    appLegacyId: 23,
    fuelLegacyId: 4,
    brand: 'Dinas',
    fuelTankCapacity: 0,
    normalFuelRatio: 1,
    normalTareWeight: 0,
    maxNetLoad: 0,
    maxNetVolume: 0,
    wheelCount: 0,
  },
  {
    legacyId: 227,
    appLegacyId: 23,
    fuelLegacyId: 3,
    brand: 'Rekanan',
    fuelTankCapacity: 0,
    normalFuelRatio: 1,
    normalTareWeight: 0,
    maxNetLoad: 0,
    maxNetVolume: 0,
    wheelCount: 0,
  },
  {
    legacyId: 228,
    appLegacyId: 23,
    fuelLegacyId: 3,
    brand: 'Swasta',
    fuelTankCapacity: 0,
    normalFuelRatio: 1,
    normalTareWeight: 0,
    maxNetLoad: 0,
    maxNetVolume: 0,
    wheelCount: 0,
  },
  {
    legacyId: 229,
    appLegacyId: 23,
    fuelLegacyId: 3,
    brand: 'Pelabuhan',
    fuelTankCapacity: 0,
    normalFuelRatio: 1,
    normalTareWeight: 0,
    maxNetLoad: 0,
    maxNetVolume: 0,
    wheelCount: 0,
  },
  {
    legacyId: 230,
    appLegacyId: 23,
    fuelLegacyId: 3,
    brand: 'Pintu Air',
    fuelTankCapacity: 0,
    normalFuelRatio: 1,
    normalTareWeight: 0,
    maxNetLoad: 0,
    maxNetVolume: 0,
    wheelCount: 0,
  },
  {
    legacyId: 231,
    appLegacyId: 24,
    fuelLegacyId: 4,
    brand: 'Dinas',
    fuelTankCapacity: 0,
    normalFuelRatio: 1,
    normalTareWeight: 0,
    maxNetLoad: 0,
    maxNetVolume: 0,
    wheelCount: 0,
  },
  {
    legacyId: 232,
    appLegacyId: 24,
    fuelLegacyId: 3,
    brand: 'Rekanan',
    fuelTankCapacity: 0,
    normalFuelRatio: 1,
    normalTareWeight: 0,
    maxNetLoad: 0,
    maxNetVolume: 0,
    wheelCount: 0,
  },
  {
    legacyId: 233,
    appLegacyId: 24,
    fuelLegacyId: 3,
    brand: 'Swasta',
    fuelTankCapacity: 0,
    normalFuelRatio: 1,
    normalTareWeight: 0,
    maxNetLoad: 0,
    maxNetVolume: 0,
    wheelCount: 0,
  },
  {
    legacyId: 234,
    appLegacyId: 24,
    fuelLegacyId: 3,
    brand: 'Pelabuhan',
    fuelTankCapacity: 0,
    normalFuelRatio: 1,
    normalTareWeight: 0,
    maxNetLoad: 0,
    maxNetVolume: 0,
    wheelCount: 0,
  },
  {
    legacyId: 235,
    appLegacyId: 24,
    fuelLegacyId: 3,
    brand: 'Pintu Air',
    fuelTankCapacity: 0,
    normalFuelRatio: 1,
    normalTareWeight: 0,
    maxNetLoad: 0,
    maxNetVolume: 0,
    wheelCount: 0,
  },
  {
    legacyId: 236,
    appLegacyId: 25,
    fuelLegacyId: 4,
    brand: 'Dinas',
    fuelTankCapacity: 0,
    normalFuelRatio: 1,
    normalTareWeight: 0,
    maxNetLoad: 0,
    maxNetVolume: 0,
    wheelCount: 0,
  },
  {
    legacyId: 237,
    appLegacyId: 25,
    fuelLegacyId: 3,
    brand: 'Rekanan',
    fuelTankCapacity: 0,
    normalFuelRatio: 1,
    normalTareWeight: 0,
    maxNetLoad: 0,
    maxNetVolume: 0,
    wheelCount: 0,
  },
  {
    legacyId: 238,
    appLegacyId: 25,
    fuelLegacyId: 3,
    brand: 'Swasta',
    fuelTankCapacity: 0,
    normalFuelRatio: 1,
    normalTareWeight: 0,
    maxNetLoad: 0,
    maxNetVolume: 0,
    wheelCount: 0,
  },
  {
    legacyId: 239,
    appLegacyId: 25,
    fuelLegacyId: 3,
    brand: 'Pelabuhan',
    fuelTankCapacity: 0,
    normalFuelRatio: 1,
    normalTareWeight: 0,
    maxNetLoad: 0,
    maxNetVolume: 0,
    wheelCount: 0,
  },
  {
    legacyId: 240,
    appLegacyId: 25,
    fuelLegacyId: 3,
    brand: 'Pintu Air',
    fuelTankCapacity: 0,
    normalFuelRatio: 1,
    normalTareWeight: 0,
    maxNetLoad: 0,
    maxNetVolume: 0,
    wheelCount: 0,
  },
  {
    legacyId: 241,
    appLegacyId: 26,
    fuelLegacyId: 4,
    brand: 'Dinas',
    fuelTankCapacity: 0,
    normalFuelRatio: 1,
    normalTareWeight: 0,
    maxNetLoad: 0,
    maxNetVolume: 0,
    wheelCount: 0,
  },
  {
    legacyId: 242,
    appLegacyId: 26,
    fuelLegacyId: 3,
    brand: 'Rekanan',
    fuelTankCapacity: 0,
    normalFuelRatio: 1,
    normalTareWeight: 0,
    maxNetLoad: 0,
    maxNetVolume: 0,
    wheelCount: 0,
  },
  {
    legacyId: 243,
    appLegacyId: 26,
    fuelLegacyId: 3,
    brand: 'Swasta',
    fuelTankCapacity: 0,
    normalFuelRatio: 1,
    normalTareWeight: 0,
    maxNetLoad: 0,
    maxNetVolume: 0,
    wheelCount: 0,
  },
  {
    legacyId: 244,
    appLegacyId: 26,
    fuelLegacyId: 3,
    brand: 'Pelabuhan',
    fuelTankCapacity: 0,
    normalFuelRatio: 1,
    normalTareWeight: 0,
    maxNetLoad: 0,
    maxNetVolume: 0,
    wheelCount: 0,
  },
  {
    legacyId: 245,
    appLegacyId: 26,
    fuelLegacyId: 3,
    brand: 'Pintu Air',
    fuelTankCapacity: 0,
    normalFuelRatio: 1,
    normalTareWeight: 0,
    maxNetLoad: 0,
    maxNetVolume: 0,
    wheelCount: 0,
  },
  {
    legacyId: 246,
    appLegacyId: 27,
    fuelLegacyId: 4,
    brand: 'Dinas',
    fuelTankCapacity: 0,
    normalFuelRatio: 1,
    normalTareWeight: 0,
    maxNetLoad: 0,
    maxNetVolume: 0,
    wheelCount: 0,
  },
  {
    legacyId: 247,
    appLegacyId: 27,
    fuelLegacyId: 3,
    brand: 'Rekanan',
    fuelTankCapacity: 0,
    normalFuelRatio: 1,
    normalTareWeight: 0,
    maxNetLoad: 0,
    maxNetVolume: 0,
    wheelCount: 0,
  },
  {
    legacyId: 248,
    appLegacyId: 27,
    fuelLegacyId: 3,
    brand: 'Swasta',
    fuelTankCapacity: 0,
    normalFuelRatio: 1,
    normalTareWeight: 0,
    maxNetLoad: 0,
    maxNetVolume: 0,
    wheelCount: 0,
  },
  {
    legacyId: 249,
    appLegacyId: 27,
    fuelLegacyId: 3,
    brand: 'Pelabuhan',
    fuelTankCapacity: 0,
    normalFuelRatio: 1,
    normalTareWeight: 0,
    maxNetLoad: 0,
    maxNetVolume: 0,
    wheelCount: 0,
  },
  {
    legacyId: 250,
    appLegacyId: 27,
    fuelLegacyId: 3,
    brand: 'Pintu Air',
    fuelTankCapacity: 0,
    normalFuelRatio: 1,
    normalTareWeight: 0,
    maxNetLoad: 0,
    maxNetVolume: 0,
    wheelCount: 0,
  },
  {
    legacyId: 251,
    appLegacyId: 28,
    fuelLegacyId: 6,
    brand: 'Dinas',
    fuelTankCapacity: 0,
    normalFuelRatio: 1,
    normalTareWeight: 0,
    maxNetLoad: 0,
    maxNetVolume: 0,
    wheelCount: 6,
  },
  {
    legacyId: 252,
    appLegacyId: 28,
    fuelLegacyId: 3,
    brand: 'Rekanan',
    fuelTankCapacity: 0,
    normalFuelRatio: 1,
    normalTareWeight: 0,
    maxNetLoad: 0,
    maxNetVolume: 0,
    wheelCount: 6,
  },
  {
    legacyId: 253,
    appLegacyId: 28,
    fuelLegacyId: 3,
    brand: 'Swasta',
    fuelTankCapacity: 0,
    normalFuelRatio: 1,
    normalTareWeight: 0,
    maxNetLoad: 0,
    maxNetVolume: 0,
    wheelCount: 6,
  },
  {
    legacyId: 254,
    appLegacyId: 28,
    fuelLegacyId: 3,
    brand: 'Pelabuhan ',
    fuelTankCapacity: 0,
    normalFuelRatio: 1,
    normalTareWeight: 0,
    maxNetLoad: 0,
    maxNetVolume: 0,
    wheelCount: 6,
  },
  {
    legacyId: 255,
    appLegacyId: 28,
    fuelLegacyId: 3,
    brand: 'Pintu Air',
    fuelTankCapacity: 0,
    normalFuelRatio: 1,
    normalTareWeight: 0,
    maxNetLoad: 0,
    maxNetVolume: 0,
    wheelCount: 6,
  },
  {
    legacyId: 256,
    appLegacyId: 3,
    fuelLegacyId: 4,
    brand: 'HINO',
    fuelTankCapacity: 0,
    normalFuelRatio: 1,
    normalTareWeight: 0,
    maxNetLoad: 0,
    maxNetVolume: 0,
    wheelCount: 6,
  },
];
