/**
 * Typed accessors for the cleaned legacy master-data fixtures (Sites, Routes,
 * Vehicles). The data lives in the sibling legacy-{sites,routes,vehicles}.json
 * files, AUTO-GENERATED by scripts/generate-legacy-fixtures.ts from the legacy
 * MySQL dump (cleanup mirrors scripts/migration/lib/{transforms,enums}.ts).
 *
 * Loaded via JSON.parse rather than imported as TS literals: a multi-thousand-row
 * array of enum-typed object literals overflows tsc's union representation
 * (TS2590). JSON.parse → typed cast sidesteps that while staying type-safe at use.
 */
import { readFileSync } from 'node:fs';
import { join } from 'node:path';

import type { EmploymentStatus, RouteCategory, SiteType, VehicleStatus } from '@prisma/client';

export interface LegacySite {
  readonly legacyId: number;
  readonly type: SiteType;
  readonly name: string;
  readonly address: string;
  readonly latitude: number | null;
  readonly longitude: number | null;
}

export interface LegacyRoute {
  readonly legacyId: number;
  readonly category: RouteCategory;
  readonly originLegacyId: number;
  readonly destinationLegacyId: number;
  readonly distanceKm: number;
}

export interface LegacyVehicle {
  readonly legacyId: number;
  readonly poolLegacyId: number;
  readonly modelLegacyId: number;
  readonly status: VehicleStatus;
  readonly plateNumber: string;
  readonly needsPlateReview: boolean;
  readonly chassisNumber: string;
  readonly engineNumber: string;
  readonly manufactureYear: number | null;
  readonly currentFuelRatio: number;
  readonly currentTareWeight: number;
  readonly currentOdometer: number;
  /** ISO yyyy-MM-dd, or null when the legacy date was 0000-00-00 (seed applies a fallback). */
  readonly registrationExpiry: string | null;
  readonly taxExpiry: string | null;
  readonly notes: string | null;
}

function load<T>(file: string): readonly T[] {
  return JSON.parse(readFileSync(join(__dirname, file), 'utf8')) as readonly T[];
}

export interface LegacyDriver {
  readonly legacyId: number;
  readonly poolLegacyId: number;
  readonly employmentStatus: EmploymentStatus;
  readonly name: string;
  readonly idCardNumber: string;
  readonly originAddress: string;
  readonly currentAddress: string;
  /** ISO yyyy-MM-dd, or null when the legacy date was 0000-00-00 (seed applies a fallback). */
  readonly birthDate: string | null;
  readonly contact: string;
  readonly safetyTraining: string | null;
  readonly notes: string | null;
}

export interface LegacyDriverLicense {
  readonly legacyId: number;
  readonly driverLegacyId: number;
  /** Resolved against the seeded LicenseClass by name (A / BI / … / D). */
  readonly licenseClassName: string;
  readonly licenseNumber: string;
  readonly expiry: string | null;
}

export const LEGACY_SITES: readonly LegacySite[] = load<LegacySite>('legacy-sites.json');
export const LEGACY_ROUTES: readonly LegacyRoute[] = load<LegacyRoute>('legacy-routes.json');
export const LEGACY_VEHICLES: readonly LegacyVehicle[] =
  load<LegacyVehicle>('legacy-vehicles.json');
export const LEGACY_DRIVERS: readonly LegacyDriver[] = load<LegacyDriver>('legacy-drivers.json');
export const LEGACY_DRIVER_LICENSES: readonly LegacyDriverLicense[] =
  load<LegacyDriverLicense>('legacy-licenses.json');
