import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

// Sidebar is auto-generated from the ./docs folder tree + each folder's
// _category_.json. Adding a markdown file (or folder) makes it appear in the
// sidebar automatically — no edit here required. This keeps the manual
// maintainable by non-developers: drop a .md in, set front-matter, done.
const sidebars: SidebarsConfig = {
  docsSidebar: [{ type: 'autogenerated', dirName: '.' }],
};

export default sidebars;
